### ISSUE TITLE
Kubelet Logs: "http: TLS handshake error from 100.64.126.1:44660: local error: tls: bad record MAC"

### ISSUE THREAD

**Issue by diranged** [DataDog/datadog-agent#12371] opened 2022-06-10 13:47 UTC
**Describe what happened:**
The `kubelet` process on our [BottleRocket](https://github.com/bottlerocket-os/bottlerocket) EKS nodes is throwing an error every 10-20 seconds in the logs. The error looks like it is coming from requests from the `datadog-agent` pod on the host:

```
Jun 10 13:42:20 ip-100-64-85-71.us-west-2.compute.internal kubelet[2074]: I0610 13:42:20.158108    2074 log.go:195] http: TLS handshake error from 100.64.126.1:56588: local error: tls: bad record MAC
Jun 10 13:42:40 ip-100-64-85-71.us-west-2.compute.internal kubelet[2074]: I0610 13:42:40.159403    2074 log.go:195] http: TLS handshake error from 100.64.126.1:44916: local error: tls: bad record MAC
Jun 10 13:43:00 ip-100-64-85-71.us-west-2.compute.internal kubelet[2074]: I0610 13:43:00.157722    2074 log.go:195] http: TLS handshake error from 100.64.126.1:51460: local error: tls: bad record MAC
Jun 10 13:43:20 ip-100-64-85-71.us-west-2.compute.internal kubelet[2074]: I0610 13:43:20.158077    2074 log.go:195] http: TLS handshake error from 100.64.126.1:54576: local error: tls: bad record MAC
Jun 10 13:43:40 ip-100-64-85-71.us-west-2.compute.internal kubelet[2074]: I0610 13:43:40.161267    2074 log.go:195] http: TLS handshake error from 100.64.126.1:52470: local error: tls: bad record MAC
Jun 10 13:44:00 ip-100-64-85-71.us-west-2.compute.internal kubelet[2074]: I0610 13:44:00.164590    2074 log.go:195] http: TLS handshake error from 100.64.126.1:56460: local error: tls: bad record MAC
```

```
bash-4.2# journalctl --directory=/.bottlerocket/rootfs/var/log/journal | grep "TLS handshake error" | wc      
   1811   38031  362248
bash-4.2# uptime
 13:45:52 up 10:04,  0 users,  load average: 1.29, 1.76, 1.79
bash-4.2# 
```

**Describe what you expected:**

I would not expect that the `datadog-agent` would cause error logs to be printed by Kubelet. This implies that the datadog agent is in some way probing the `kubelet` HTTP endpoint and causing these errors.

**Additional environment details (Operating System, Cloud provider, etc):**

EKS: 1.22
BottleRocket: 1.7.2. or 1.8.0
Datadog Agent: 7.36.0

**Comment by pgarrett-ibm** [comment] 2022-09-01 16:00
I'm seeing this also, on non-bottlerocket nodes.
EKS: 1.23
AMI: 1.23.9-20220824
Datadog Agent: Agent 7.36.1 - Commit: 95e1e89 - Serialization version: v5.0.19 - Go version: go1.17.6

```
# journalctl | grep "TLS handshake error" | wc
    491   10313   93173
```

**Comment by Ramyak** [comment] 2022-09-09 17:30
We at Airbnb are seeing this as well.

| datadog-agent version | Errors | Comments|
|------------------------|--------|-----------|
| 7.26.0                              | None ||
| 7.35.2 | None | |
| 7.36.1 | `log.go:181] http: TLS handshake error from 172.21.145.36:39154: local error: tls: bad record MAC`|  Potential change that caused this: `Collect liveness and readiness probe metrics` #11682 https://github.com/DataDog/integrations-core/pull/11682 |
| 7.38.2| `log.go:181] http: TLS handshake error from 100.123.77.110:57470: local error: tls: bad record MAC`||
|7.39 ?| - |No debian package released yet. But potential fix: `Fix probe metrics not reported when creds required` https://github.com/DataDog/integrations-core/pull/12642 |

* @ahmed-mez can you confirm this?
* Could you give a timeline on when 7.39 debian package would be released?

**Comment by ahmed-mez** [comment] 2022-09-12 07:54
7.39.0 will be released in the coming days, I can't guarantee 100% that https://github.com/DataDog/integrations-core/pull/12642 is the fix for the kubelet errors you're seeing without further details.
It's best to [open a support ticket](https://www.datadoghq.com/support/) so we can help you confirm the root cause. Thanks!

**Comment by Ramyak** [comment] 2022-09-12 19:09
7.39 was released over the weekend and it **did** fix the issue.

Thank you.

**Closed** 2022-09-13 07:23 UTC
Labels: team/containers

**Comment by sema4-dmytrobazulin** [comment] 2022-09-17 04:40
> 7.39 was released over the weekend and it **did** fix the issue.
> 
> Thank you.

wish it was communicated a little better. In our experience on AWS EKS behind each log line there is a zombie process in the DD Agent container and it was depleting available process/thread count on the node, effectively brining node down within few days. Caused few headaches.
