### ISSUE TITLE
apparmor="DENIED" logs for process-agent and agent

### ISSUE THREAD

**Issue by coryallegory** [DataDog/datadog-agent#6915] opened 2020-12-04 18:07 UTC
After adding the full datadog agent resources to our kubernetes cluster, I noticed a lot of log entries for

```
<...> kernel: audit: type=1400 audit(1607103503.457:484552): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=219278 comm="process-agent" requested_mask="trace" denied_mask="trace" peer="unconfined"`
<...> audit[219278]: AVC apparmor="DENIED" operation="ptrace" profile="docker-default" pid=219278 comm="process-agent" requested_mask="trace" denied_mask="trace" peer="unconfined"`
```

These resources were used as per the datadog help docs
https://docs.datadoghq.com/resources/yaml/datadog-agent-all-features.yaml

After reading around, I figured out that the issue was with the `process-agent` and `agent` images specifically. `system-probe` is the only image flagged with apparmor as `unconfined` in the agent yaml linked directly above. Adding the following to the daemonset `spec.template.metadata.annotations` seems to have fixed the apparmor=denied issue.

```
container.apparmor.security.beta.kubernetes.io/process-agent: unconfined
container.apparmor.security.beta.kubernetes.io/agent: unconfined
```

Would this be a problem with my setup, or do the datadog agent resources need some attention for this?
https://docs.datadoghq.com/resources/yaml/datadog-agent-all-features.yaml

Running Ubuntu 18.04.2, kubernetes 1.19.3, docker 10.03.6

**Comment by moazrefat** [comment] 2020-12-08 12:12
We have slightly different versions of ubuntu and kubernetes but still this describes exactly what we are having too.

**Comment by L3n41c** [comment] 2020-12-09 13:55
Hello @coryallegory,

Thanks for reporting this issue.

Here is what I tried to reproduce the issue you are describing:
* I started an AWS EKS 1.17 cluster with Ubuntu 18.04.5 nodes. (Because EKS 1.18 supports only Ubuntu 20.04 nodes and and EKS doesn’t support 1.19 yet). Docker version is 17.03.2-ce.
* I deployed the datadog agent with the manifest you mentioned:
```
kubectl create ns datadog-agent
curl https://docs.datadoghq.com/resources/yaml/datadog-agent-all-features.yaml | sed "s/PUT_YOUR_BASE64_ENCODED_API_KEY_HERE/$(echo $DD_API_KEY | base64)/; s/namespace: default/namespace: datadog-agent/" | kubectl --namespace datadog-agent apply -f -
kubectl --namespace datadog-agent create sa datadog-agent
```

I then checked the following things on the node:
* datadog agents are running with the standard `docker-default` AppArmor profile. Only `system-probe` is `unconfined`:
```
root@ip-172-29-97-166:~# ps aux | grep agent
root     26762  0.7  1.4 1657348 114800 ?      SLsl 12:50   0:09 agent run
root     26829  0.1  0.5 1260448 39552 ?       SLsl 12:50   0:01 trace-agent -config=/etc/datadog-agent/datadog.yaml
root     26919  0.5  0.8 1354132 69108 ?       SLsl 12:50   0:07 process-agent -config=/etc/datadog-agent/datadog.yaml
root     27038  0.2  1.3 1575156 104616 ?      Ssl  12:50   0:03 /opt/datadog-agent/embedded/bin/system-probe --config=/etc/datadog-agent/system-probe.yaml

root@ip-172-29-97-166:~# aa-status
apparmor module is loaded.
25 profiles are loaded.
19 profiles are in enforce mode.
[…]
   docker-default
[…]
6 profiles are in complain mode.
[…]
11 processes have profiles defined.
9 processes are in enforce mode.
[…]
   docker-default (26762)
   docker-default (26829)
   docker-default (26919)
2 processes are in complain mode.
   snap.amazon-ssm-agent.amazon-ssm-agent (1588)
   snap.kubelet-eks.daemon (7020)
0 processes are unconfined but have a profile defined.
```

* Check the `audit` log. I found no AppArmor denial for any agent or about ptrace:
```
root@ip-172-29-97-166:~# journalctl -t kernel | grep audit | grep DENIED
root@ip-172-29-97-166:~# journalctl -t kernel | grep audit | grep ptrace
root@ip-172-29-97-166:~# journalctl -t kernel | grep audit | grep agent
Dec 09 11:00:45 ip-172-29-97-166 kernel: audit: type=1400 audit(1607511645.183:21): apparmor="STATUS" operation="profile_load" profile="unconfined" name="snap.amazon-ssm-agent.amazon-ssm-agent" pid=1555 comm="apparmor_parser"
Dec 09 11:00:45 ip-172-29-97-166 kernel: audit: type=1400 audit(1607511645.183:22): apparmor="STATUS" operation="profile_load" profile="unconfined" name="snap-update-ns.amazon-ssm-agent" pid=1554 comm="apparmor_parser"
Dec 09 11:00:45 ip-172-29-97-166 kernel: audit: type=1400 audit(1607511645.187:23): apparmor="STATUS" operation="profile_load" profile="unconfined" name="snap.amazon-ssm-agent.ssm-cli" pid=1556 comm="apparmor_parser"
```

@coryallegory Unfortunately, I wasn’t able to reproduce this issue. Would you have a self-contained reproducer ?

**Comment by L3n41c** [comment] 2020-12-18 13:13
After investigation, it seems that the AppArmor `ptrace` denial logs are cause by `irqbalance`.
In order to confirm it, one can try to stop this service with `systemctl stop irqbalance` and check that AppArmor stops logging those `ptrace` denials.

Alternatively, in order to stop AppArmor logs without shutting down `irqbalance`, it’s possible to use a custom AppArmor profile by following these steps:

1. Create a `/etc/apparmor.d/docker-dd-agent` file with this content:
```
#include <tunables/global>

profile docker-datadog-agent flags=(attach_disconnected,mediate_deleted) {
  #include <abstractions/base>
  network,
  capability,
  file,
  umount,

  # Host (privileged) processes may send signals to container processes.
  signal (receive) peer=unconfined,
  # dockerd may send signals to container processes (for "docker kill").
  signal (receive) peer=unconfined,
  # Container processes may send signals amongst themselves.
  signal (send,receive) peer=docker-datadog-agent,

  deny @{PROC}/* w,   # deny write for all files directly in /proc (not in a subdir)
  # deny write to files not in /proc/<number>/** or /proc/sys/**
  deny @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9][^0-9][^0-9][^0-9]*}/** w,
  deny @{PROC}/sys/[^k]** w,  # deny /proc/sys except /proc/sys/k* (effectively /proc/sys/kernel)
  deny @{PROC}/sys/kernel/{?,??,[^s][^h][^m]**} w,  # deny everything except shm* in /proc/sys/kernel/
  deny @{PROC}/sysrq-trigger rwklx,
  deny @{PROC}/kcore rwklx,
  deny mount,
  deny /sys/[^f]*/** wklx,
  deny /sys/f[^s]*/** wklx,
  deny /sys/fs/[^c]*/** wklx,
  deny /sys/fs/c[^g]*/** wklx,
  deny /sys/fs/cg[^r]*/** wklx,
  deny /sys/firmware/** rwklx,
  deny /sys/kernel/security/** rwklx,

  # suppress ptrace denials when using 'docker ps' or using 'ps' inside a container
  ptrace (trace,read,tracedby,readby) peer=docker-datadog-agent,

  # suppress ptrace denials when agent and process-agent are accessing /proc
  ptrace (read),
}
```

2. Load the dedicated AppArmor profile with this command:
```sh
apparmor_parser /etc/apparmor.d/docker-dd-agent
```

3. Change the AppArmor profile of the agent and process-agent by adding the following annotations to the Datadog agent DaemonSet pod template:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog-agent
spec:
  selector:
    matchLabels:
      app: datadog-agent
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/agent: localhost/docker-datadog-agent
        container.apparmor.security.beta.kubernetes.io/process-agent: localhost/docker-datadog-agent
      labels:
        app: datadog-agent
      name: datadog-agent
    spec:
[…]
```

**Comment by mvisonneau** [comment] 2021-02-08 16:09
interesting issue, I happened to face it on Ubuntu 20.04.2 / containerd 1.4.3 on `arm64` based instances but not `amd64`.

Disabling irqbalance had no effect but adding the dedicated apparmor profile fixed the issue 👍 

thanks @L3n41c! 🙇

**Comment by L3n41c** [comment] 2021-03-05 14:46
Closing this issue as the proposed AppArmor profile seems to properly fix the AppArmor log.

**Closed by L3n41c** 2021-03-05 14:46 UTC

**Comment by dehy** [comment] 2021-05-04 11:39
Do you know how I could use this AppArmor profile from a Docker Swarm Stack? I have never used k8s and don't fully understand the DaemonSet configuration impact.

I'm using ubuntu 20.04.2 and get regular DENIED logs:
```
May  4 13:35:59 web2 kernel: [451112.562718] audit: type=1400 audit(1620128159.047:185580): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=155275 comm="process-agent" requested_mask="read" denied_mask="read" peer="unconfined"
May  4 13:35:59 web2 kernel: [451112.562732] audit: type=1400 audit(1620128159.047:185581): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=155275 comm="process-agent" requested_mask="read" denied_mask="read" peer="unconfined"
May  4 13:35:59 web2 kernel: [451112.564162] audit: type=1400 audit(1620128159.047:185582): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=155275 comm="process-agent" requested_mask="read" denied_mask="read" peer="unconfined"
May  4 13:35:59 web2 kernel: [451112.564175] audit: type=1400 audit(1620128159.047:185583): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=155275 comm="process-agent" requested_mask="read" denied_mask="read" peer="unconfined"
May  4 13:36:09 web2 kernel: [451122.562327] audit: type=1400 audit(1620128169.047:185584): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=155275 comm="process-agent" requested_mask="read" denied_mask="read" peer="unconfined"
May  4 13:36:09 web2 kernel: [451122.562703] audit: type=1400 audit(1620128169.047:185585): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=155275 comm="process-agent" requested_mask="read" denied_mask="read" peer="unconfined"
May  4 13:36:09 web2 kernel: [451122.562715] audit: type=1400 audit(1620128169.047:185586): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=155275 comm="process-agent" requested_mask="read" denied_mask="read" peer="unconfined"
May  4 13:36:09 web2 kernel: [451122.562723] audit: type=1400 audit(1620128169.047:185587): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=155275 comm="process-agent" requested_mask="read" denied_mask="read" peer="unconfined"
May  4 13:36:19 web2 kernel: [451132.575434] audit: type=1400 audit(1620128179.059:185588): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=155275 comm="process-agent" requested_mask="read" denied_mask="read" peer="unconfined"
May  4 13:36:19 web2 kernel: [451132.576710] audit: type=1400 audit(1620128179.059:185589): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=155275 comm="process-agent" requested_mask="read" denied_mask="read" peer="unconfined"
May  4 13:36:19 web2 kernel: [451132.576723] audit: type=1400 audit(1620128179.063:185590): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=155275 comm="process-agent" requested_mask="read" denied_mask="read" peer="unconfined"
May  4 13:36:19 web2 kernel: [451132.576732] audit: type=1400 audit(1620128179.063:185591): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=155275 comm="process-agent" requested_mask="read" denied_mask="read" peer="unconfined"
```

thank you!

**Comment by NicklasWallgren** [comment] 2022-03-10 10:53
@L3n41c We tried with the `docker-datadog-agent` profile that you provided above, and it doesn't seem to work, at least not anymore.  

We hade to use `unconfined` for the `agent` as well as the `process-agent`

```
# agents.podAnnotations -- Annotations to add to the DaemonSet's Pods
  podAnnotations:
    container.apparmor.security.beta.kubernetes.io/agent: "unconfined"
    container.apparmor.security.beta.kubernetes.io/process-agent: "unconfined"
```
