### ISSUE TITLE
[BUG] system-probe failed to create containerd task

### ISSUE THREAD

**Issue by ThangEthan** [DataDog/datadog-agent#13436] opened 2022-09-09 10:24 UTC
During helm installation. system-probe pod failed to start

**Agent Environment**
gcr.io/datadoghq/cluster-agent:1.22.0
gcr.io/datadoghq/agent:7.38.2

**Describe what happened:**
During helm installation. system-probe pod failed to start with this messages: Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec /opt/datadog-agent/embedded/bin/system-probe: operation not permitted: unknown

**Describe what you expected:**
All pod running

**Steps to reproduce the issue:**
helm install -f resources/datadog-values.yaml datadog-monitoring --namespace datadog-system datadog/datadog 

**Additional environment details (Operating System, Cloud provider, etc):**
Kubernetes version 1.24.4
Container runtime: containerd

**Comment by ViniciusBastosTR** [comment] 2022-09-14 20:28
Same issue here.
K8S Version: v1.21.7

**Comment by bencouture** [comment] 2022-09-20 14:59
Also seeing this exact same error, running these versions:
datadoghq/agent:7.38.2
kube version: v1.19.7

**Comment by MarcioCruzTR** [comment] 2022-09-21 21:17
Same issue here.
datadoghq/agent:7.37.1
K8S Version: v1.21.7

**Comment by ViniciusBastosTR** [comment] 2022-09-21 21:19
System probe container is returning message below:
Message:      failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec /opt/datadog-agent/embedded/bin/system-probe: operation not permitted: unknown

**Comment by brycekahle** [comment] 2022-09-26 18:09
Is anyone able to get logs from a failed `system-probe` container? If you use the `-p` argument to `kubectl logs`, you can get logs from a previous container. If you are not comfortable putting them here, please open a support case at https://help.datadoghq.com/hc/en-us/requests/new

**Comment by froth** [comment] 2022-09-28 09:23
Fetching logs for ```kubectl logs  datadog-XXXX -c system-probe``` yields an empty output. I believe the probe is not even able to write logs.

**Comment by Go2Engle** [comment] 2022-09-28 14:21
@froth I too am having the same issue. When running the command above it just returns blank.

**Comment by froth** [comment] 2022-09-28 14:44
> @froth Can you try with `-p`, `kubectl logs -p datadog-XXXX -c system-probe`? If the container is crashing, I would expect getting logs for the current container to work. Getting the previous logs should.

Same result

**Comment by brycekahle** [comment] 2022-09-28 14:50
@froth Got it. We can try to reproduce. Any other relevant details about your setup? Are you using EKS, GKE, or another cloud k8s setup?

**Comment by froth** [comment] 2022-09-28 15:10
We are experiencing this on EKS

**Comment by Go2Engle** [comment] 2022-09-28 15:18
We are having the issue on prem Ubuntu 20.04.5 LTS running in vsphere.

**Comment by brycekahle** [comment] 2022-09-28 17:02
@froth do you know what Helm chart version you have?

**Comment by Go2Engle** [comment] 2022-09-28 17:54
I know we have tried 3.1.3 and even downgraded back to 2.37.7 that we were running before but still have issues on either version.

**Comment by brycekahle** [comment] 2022-09-28 17:58
@Go2Engle what version of the agent are you trying?

**Comment by Go2Engle** [comment] 2022-09-28 18:00
@brycekahle tried 7.38.2 and even 7.39.0

**Comment by brycekahle** [comment] 2022-09-28 19:17
Is anyone running SELinux?

**Comment by Go2Engle** [comment] 2022-09-28 19:21
we are not

**Comment by brycekahle** [comment] 2022-09-28 19:29
@Go2Engle since it says "operation not permitted", which is usually `EPERM`, can you take a look at the host kernel logs to see if anything jumps out? I'm having trouble reproducing this error.

**Comment by brycekahle** [comment] 2022-09-28 19:33
Also check the output of `cat /sys/kernel/security/lockdown`

**Comment by Go2Engle** [comment] 2022-09-28 19:36
in `/var/log/kernlog` there are many instances of the below
`Sep 28 15:31:45 dev-k8s-wrk-02 kernel: [17025663.143951] audit: type=1400 audit(1664393505.656:77529857): apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=2822187 comm="agent" requested_mask="read" denied_mask="read" peer="unconfined"`

when running `cat /sys/kernel/security/lockdown` it outputs the below
`[none] integrity confidentiality`

**Comment by Go2Engle** [comment] 2022-09-28 19:38
when viewing the system-probe container in lens I get this as the last status if that helps also.
```
Last Status
terminated
Reason:Reason: StartError - exit code: 128
```

**Comment by Go2Engle** [comment] 2022-09-28 19:44
in syslog there is the below might help?
```
Sep 28 15:35:55 dev-k8s-wrk-02 kubelet[2263280]: E0928 15:35:55.858243 2263280 kuberuntime_manager.go:905] container &Container{Name:system-probe,Image:gcr.io/datadoghq/agent:7.39.0,Command:[/opt/datadog-agent/embedded/bin/system-probe --config=/etc/datadog-agent/system-probe.yaml],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{EnvVar{Name:GODEBUG,Value:x509ignoreCN=0,ValueFrom:nil,},EnvVar{Name:DD_API_KEY,Value:,ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:&SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:datadog,},Key:api-key,Optional:nil,},},},EnvVar{Name:DD_KUBERNETES_KUBELET_HOST,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:status.hostIP,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:DD_KUBELET_TLS_VERIFY,Value:false,ValueFrom:nil,},EnvVar{Name:DD_CLUSTER_NAME,Value:dev-k8s,ValueFrom:nil,},EnvVar{Name:KUBERNETES,Value:yes,ValueFrom:nil,},EnvVar{Name:DD_LOG_LEVEL,Value:INFO,ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:logdatadog,ReadOnly:false,MountPath:/var/log/datadog,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:tmpdir,ReadOnly:false,MountPath:/tmp,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:debugfs,ReadOnly:false,MountPath:/sys/kernel/debug,SubPath:,MountPropagation:*None,SubPathExpr:,},VolumeMount{Name:config,ReadOnly:false,MountPath:/etc/datadog-agent,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:sysprobe-config,ReadOnly:false,MountPath:/etc/datadog-agent/system-probe.yaml,SubPath:system-probe.yaml,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:sysprobe-socket-dir,ReadOnly:false,MountPath:/var/run/sysprobe,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:procdir,ReadOnly:true,MountPath:/host/proc,SubPath:,MountPropagation:*None,SubPathExpr:,},VolumeMount{Name:os-release-file,ReadOnly:true,MountPath:/host/etc/os-release,SubPath:,MountPropagation:*None,SubPathExpr:,},VolumeMount{Name:etc-redhat-release,ReadOnly:true,MountPath:/host/etc/redhat-release,SubPath:,MountPropagation:*None,SubPathExpr:,},VolumeMount{Name:etc-fedora-release,ReadOnly:true,MountPath:/host/etc/fedora-release,SubPath:,MountPropagation:*None,SubPathExpr:,},VolumeMount{Name:etc-lsb-release,ReadOnly:true,MountPath:/host/etc/lsb-release,SubPath:,MountPropagation:*None,SubPathExpr:,},VolumeMount{Name:kube-api-access-frn82,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:&SecurityContext{Capabilities:&Capabilities{Add:[SYS_ADMIN SYS_RESOURCE SYS_PTRACE NET_ADMIN NET_BROADCAST NET_RAW IPC_LOCK CHOWN],Drop:[],},Privileged:*false,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,SeccompProfile:&SeccompProfile{Type:Localhost,LocalhostProfile:*system-probe,},},Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} start failed in pod datadog-r89t2_observability(be385684-9920-4c2c-994a-039ff14381d0): RunContainerError: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec /opt/datadog-agent/embedded/bin/system-probe: operation not permitted: unknown
Sep 28 15:35:55 dev-k8s-wrk-02 kubelet[2263280]: E0928 15:35:55.858281 2263280 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"system-probe\" with RunContainerError: \"failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec /opt/datadog-agent/embedded/bin/system-probe: operation not permitted: unknown\"" pod="observability/datadog-r89t2" podUID=be385684-9920-4c2c-994a-039ff14381d0
Sep 28 15:35:56 dev-k8s-wrk-02 kubelet[2263280]: E0928 15:35:56.635534 2263280 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"system-probe\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=system-probe pod=datadog-r89t2_observability(be385684-9920-4c2c-994a-039ff14381d0)\"" pod="observability/datadog-r89t2" podUID=be385684-9920-4c2c-994a-039ff14381d0

```

**Comment by brycekahle** [comment] 2022-09-28 19:54
@Go2Engle ok, seems like AppArmor is preventing it from running. Can you try updating your helm `values.yaml` with the following to see if that allows system-probe to start:

```
agents:
  podSecurity:
    apparmor:
      enabled: false
```

**Comment by Go2Engle** [comment] 2022-09-28 20:06
same issue :(

**Comment by brycekahle** [comment] 2022-09-28 20:11
@Go2Engle Are you still getting `audit` entries in `/var/log/kernlog`?

**Comment by Go2Engle** [comment] 2022-09-28 20:17
yep killed pod to let it recreate to double check and this was generated
```
Sep 28 16:15:03 dev-k8s-wrk-02 kernel: [17028260.731556] audit: type=1400 audit(1664396103.341:77530827): apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=2998028 comm="agent" requested_mask="read" denied_mask="read" peer="unconfined"
Sep 28 16:15:03 dev-k8s-wrk-02 kernel: [17028260.731622] audit: type=1400 audit(1664396103.341:77530828): apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=2998028 comm="agent" requested_mask="read" denied_mask="read" peer="unconfined"
Sep 28 16:15:03 dev-k8s-wrk-02 kernel: [17028260.734435] audit: type=1400 audit(1664396103.345:77530829): apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=2998028 comm="agent" requested_mask="read" denied_mask="read" peer="unconfined"
Sep 28 16:15:03 dev-k8s-wrk-02 kernel: [17028260.734498] audit: type=1400 audit(1664396103.345:77530830): apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=2998028 comm="agent" requested_mask="read" denied_mask="read" peer="unconfined"
Sep 28 16:15:03 dev-k8s-wrk-02 kernel: [17028260.734909] audit: type=1400 audit(1664396103.345:77530831): apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=2998028 comm="agent" requested_mask="read" denied_mask="read" peer="unconfined"
Sep 28 16:15:03 dev-k8s-wrk-02 kernel: [17028260.734983] audit: type=1400 audit(1664396103.345:77530832): apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=2998028 comm="agent" requested_mask="read" denied_mask="read" peer="unconfined"
Sep 28 16:15:03 dev-k8s-wrk-02 kernel: [17028260.738545] audit: type=1400 audit(1664396103.349:77530833): apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=2998028 comm="agent" requested_mask="read" denied_mask="read" peer="unconfined"
Sep 28 16:15:03 dev-k8s-wrk-02 kernel: [17028260.738637] audit: type=1400 audit(1664396103.349:77530834): apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=2998028 comm="agent" requested_mask="read" denied_mask="read" peer="unconfined"
Sep 28 16:15:03 dev-k8s-wrk-02 kernel: [17028260.739669] audit: type=1400 audit(1664396103.349:77530835): apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=2998028 comm="agent" requested_mask="read" denied_mask="read" peer="unconfined"
Sep 28 16:15:03 dev-k8s-wrk-02 kernel: [17028260.739753] audit: type=1400 audit(1664396103.349:77530836): apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=2998028 comm="agent" requested_mask="read" denied_mask="read" peer="unconfined"
```

**Comment by brycekahle** [comment] 2022-09-28 22:33
@froth you said you were having this problem in EKS. Are you using Amazon Linux 2 or another AMI?

**Comment by froth** [comment] 2022-09-29 06:47
> @froth you said you were having this problem in EKS. Are you using Amazon Linux 2 or another AMI?

We are using Bottlerocket.

Sorry for the delay, was time to sleep where I live ;)

**Comment by brycekahle** [comment] 2022-09-29 16:48
@froth Kein Problem. I'll take a look at Bottlerocket soon. Has it worked for you in the past?

**Comment by Go2Engle** [comment] 2022-09-29 16:54
@froth and @brycekahle looking in bottlerocket open issues there is this: https://github.com/bottlerocket-os/bottlerocket/issues/2394

@brycekahle in our case just as some more background we have recently upgraded 2 clusters both running k8s v1.22 and ubuntu 20.04.3 -> k8s v1.24.6 and ubuntu 20.04.5. The thing that is odd 1 cluster datadog is running with no issues even though OS and k8s are identical to the other cluster.

**Comment by brycekahle** [comment] 2022-09-29 17:03
@Go2Engle That issue seems to be caused by `faccessat2` missing from the seccomp profile, which was fixed in `3.0.3` of the helm chart.

**Comment by brycekahle** [comment] 2022-09-29 17:07
@Go2Engle Do you know if you were using `containerd` before your upgrade?

**Comment by Go2Engle** [comment] 2022-09-29 17:09
> @Go2Engle Do you know if you were using `containerd` before your upgrade?

We were. These nodes have been on containerd since day one.

**Comment by Go2Engle** [comment] 2022-09-29 17:52
> @Go2Engle That issue seems to be caused by `faccessat2` missing from the seccomp profile, which was fixed in `3.0.3` of the helm chart.

when deploying the chart i do notice this message `spec.template.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/system-probe]: deprecated since v1.19, non-functional in v1.25+; use the "seccompProfile" field instead`

**Comment by froth** [comment] 2022-09-29 18:08
> @froth Kein Problem. I'll take a look at Bottlerocket soon. Has it worked for you in the past?

It's a fresh EKS install for evaluation, so it did not have a chance to work in the past ;). Thanks for having a look and the link to the Bottle rocket issue.

**Comment by brycekahle** [comment] 2022-09-29 19:23
@froth I spun up an EKS bottlerocket cluster and had no errors deploying the agent + NPM using Helm. Can you give me some more details about versions, architecture, agent features enabled, etc.?

**Comment by brycekahle** [comment] 2022-09-29 19:31
I found this related issue https://github.com/DataDog/datadog-agent/issues/6915

**Comment by Go2Engle** [comment] 2022-09-30 00:06
I tried adding the below but did not make a change
```
agents:
  podAnnotations:
    container.apparmor.security.beta.kubernetes.io/agent: unconfined
    container.apparmor.security.beta.kubernetes.io/process-agent: unconfined
```

**Comment by froth** [comment] 2022-09-30 09:07
> @froth I spun up an EKS bottlerocket cluster and had no errors deploying the agent + NPM using Helm. Can you give me some more details about versions, architecture, agent features enabled, etc.?

I will come back with this information on Tuesday because of public hollidays and stuff here. Sorry for the delay.

**Comment by dlorent** [comment] 2022-09-30 10:53
We are also having issues with system-probe (networkMonitoring, enabled: True) 

`  Warning  Failed     5m37s (x2 over 5m39s)  kubelet, XXXXXX  Error: failed to start container "system-probe": Error response from daemon: OCI runtime create failed: runc create failed: unable to start container process: exec /opt/datadog-agent/embedded/bin/system-probe: operation not permitted: unknown

Annotations: 
                container.apparmor.security.beta.kubernetes.io/agent: unconfined
                container.apparmor.security.beta.kubernetes.io/process-agent: unconfined
                container.apparmor.security.beta.kubernetes.io/system-probe: unconfined
                container.seccomp.security.alpha.kubernetes.io/system-probe: localhost/system-probe


NAME    NAMESPACE       REVISION        UPDATED                                         STATUS          CHART           APP VERSION
datadog datadog         51              2022-09-30 12:37:56.731257553 +0200 CEST        deployed        datadog-3.1.3   7

Image:         gcr.io/datadoghq/agent:7.39.0

OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
Ubuntu 18.04.6 LTS   4.15.0-193-generic   docker://18.9.7`

**Comment by Go2Engle** [comment] 2022-09-30 11:36
So I commented out `networkMonitoring, enabled: True` in or values which makes system-probe non existent but oddly enough I'm still getting network data for the containers?

**Comment by brycekahle** [comment] 2022-09-30 17:02
Yeah, I think the apparmor errors are a problem, but not what is causing `system-probe` to not start. This is especially true since the errors mention `agent` and `process-agent`, but not `system-probe`. 

We are trying to reproduce the system-probe start problem internally so we can narrow in on the fix.

**Comment by froth** [comment] 2022-10-04 08:51
> @froth I spun up an EKS bottlerocket cluster and had no errors deploying the agent + NPM using Helm. Can you give me some more details about versions, architecture, agent features enabled, etc.?

Kubernetes Server Version:
```Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.13-eks-15b7512", GitCommit:"94138dfbea757d7aaf3b205419578ef186dd5efb", GitTreeState:"clean", BuildDate:"2022-08-31T19:15:48Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}```

helm chart:
```datadog-2.37.4```

datadog agent:
```root@datadog-6dkfx:/# agent  version
Agent 7.38.2```

deployment fails when we set `networkMonitoring` to enabled: true

Anything more I can provide?

**Comment by AlvaroCostaAbreu** [comment] 2022-10-04 18:08
Hi everyone. 
I have the same issue here. 
Ubuntu LTS 20.04.5
K8s V.1.22.11
Helm-chart 3.1.6
Datadog Agent 7.39.1

- I Fixed this issue just disabling the Conntrack feature:
`datadog.systemProbe.enableConntrack: false`

In default values.yaml near 476 line:

 ```
systemProbe:
    # datadog.systemProbe.debugPort -- Specify the port to expose pprof and expvar for system-probe agent
    debugPort: 0
    # datadog.systemProbe.enableConntrack -- Enable the system-probe agent to connect to the netlink/conntrack subsystem to add NAT information to connection data
    ## ref: http://conntrack-tools.netfilter.org/
    enableConntrack: false
```

I'm not sure what kind of metric or facet we loses without this feature, but works here...

**Comment by brycekahle** [comment] 2022-10-04 18:32
Turning off conntrack can have a pretty significant effect on the data quality for NPM, if NAT is used at all. NAT is quite common in containerized/k8s environments. If you start to see your NPM data not correctly resolving the source or destination, that would probably be why.

**Comment by brycekahle** [comment] 2022-10-04 18:33
@AlvaroCostaAbreu what error message were you getting before turning off `conntrack`?

**Comment by brycekahle** [comment] 2022-10-04 18:36
@froth can you try with the newest helm chart version `3.1.7`?

**Comment by AlvaroCostaAbreu** [comment] 2022-10-04 18:50
> Turning off conntrack can have a pretty significant effect on the data quality for NPM, if NAT is used at all. NAT is quite common in containerized/k8s environments. If you start to see your NPM data not correctly resolving the source or destination, that would probably be why.

@brycekahle  - Now, i turning on the 'conntrack' to answer you and 'Voila' is't working. 
During my debug process i adjust the  parameter: `seccomp:` with removing 'localhost' of the path file.

**Comment by Go2Engle** [comment] 2022-10-04 19:05
Just tested chart 3.1.7 and im still having the same error.

**Comment by dlorent** [comment] 2022-10-05 07:21
I also just tested with 3.1.7 ( 7.39.1) and while enabling networkMonitoring, i got

```Error: failed to start container "system-probe": Error response from daemon: OCI runtime create failed: runc create failed: unable to start container process: exec /opt/datadog-agent/embedded/bin/system-probe: operation not permitted: unknown```

**Comment by bencouture** [comment] 2022-10-05 15:40
I upgraded to 3.1.8, verified that `rseq` and `clone3` were actually added to `/var/lib/kubelet/seccomp/system-probe` (basically just verified that the changes in the PR were actually applied to the host), then completely rebooted the host and recreated the Pod for good measure. Same exact error message. I uploaded a flare from the Pod on that host, attached to case 944682.

**Comment by brycekahle** [comment] 2022-10-05 16:45
@dlorent @bencouture Can you both detail versions of your setup (OS/distro, k8s, containerd, runc, agent, helm chart)? We are trying to find a common change that might help us identify where the problem is.

**Comment by bencouture** [comment] 2022-10-05 17:01
| package | version |
| --- | --- |
| OS | `Ubuntu 18.04.5 LTS` |
| kernel | `5.4.0-1055-aws` |
| Helm itself | `v2.16.8-rancher1` |
| Helm chart | `3.1.8` |
| Kubernetes | `v1.19.7` |
| containerd.io | `1.6.8-1` |
| runc | `1.1.4` |
| agent | `7.32.4` |

More background: we know for a fact that this issue happened when we upgraded from containerd.io `1.5.11-1` (which uses runc `1.0.3`) to containerd.io `1.6.8-1` (which uses runc `1.1.4`). If we downgrade the containerd.io version, then system-probe starts up with no issue. When we upgrade again, then it goes back to a CrashLoopBackOff.

**Comment by Go2Engle** [comment] 2022-10-05 17:03
@bencouture I would say thats when the issue started for us as well. After containerd upgrade. Have not tired downgrading but seems like that may be the common denominator!

**Comment by brycekahle** [comment] 2022-10-05 17:30
@bencouture Thanks! That is very helpful information

**Comment by Go2Engle** [comment] 2022-10-05 19:49
@brycekahle YAY! Got a healthy `system-probe` container running! looks like that did the trick!

**Comment by bencouture** [comment] 2022-10-05 20:04
Yep, that did it! Healthy on all 30+ nodes in the cluster.

**Comment by dlorent** [comment] 2022-10-06 07:49
> Alright folks, helm chart `3.1.9` should solve your woes.
> 
> @bencouture @Go2Engle @froth @dlorent @AlvaroCostaAbreu @ViniciusBastosTR @MarcioCruzTR @ThangEthan

Fantastic! tested on +60 nodes, and it's working! :) thanks!

**Comment by smg-serkly** [comment] 2022-10-07 07:35
Thanks, brycekahle! Had the same issue!

**Closed** 2022-10-07 16:28 UTC
Labels: team/networks, team/ebpf-platform

**Comment by nashtakealot** [comment] 2022-11-21 07:36
Getting this exception with Kubernetes Operator on AWS EKS. [Chart version 0.9.1](https://artifacthub.io/packages/helm/datadog/datadog-operator) 

```
Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec /opt/datadog-agent/embedded/bin/system-probe: operation not permitted: unknown
```

I enabled the operator systemprobe via the environment variable: `DD_SYSTEM_PROBE_SERVICE_MONITORING_ENABLED`

**Comment by blongman-snapdocs** [comment] 2022-11-22 17:43
@nashmrd Getting the same thing in a cluster that I rebuilt the node groups on.  Difference is that we're on an old version of the chart - 2.27.0.  It looks like we didn't pin the version of datadog, just the chart version.  I'm guessing that the chart pulls the latest version of datadog, and we're just too far behind drift.

I'm currently looking for a solution that don't require a major version upgrade on the chart.

**Comment by Go2Engle** [comment] 2022-11-22 17:50
> @nashmrd Getting the same thing in a cluster that I rebuilt the node groups on. Difference is that we're on an old version of the chart - 2.27.0. It looks like we didn't pin the version of datadog, just the chart version. I'm guessing that the chart pulls the latest version of datadog, and we're just too far behind drift.
> 
> I'm currently looking for a solution that don't require a major version upgrade on the chart.

I safely updated from 2 to 3 during this troubleshooting with no issues. I know all env's are different but seems like the agent is pretty safe to update. I used my same values files and everything.

**Comment by blongman-snapdocs** [comment] 2022-11-22 18:11
> I safely updated from 2 to 3 during this troubleshooting with no issues. I know all env's are different but seems like the agent is pretty safe to update. I used my same values files and everything.

That worked.  I expect that sort of thing to not work.  Thanks.  They've started.  I'm updating my terraform to make it so the chart version is a variable, and will put together a project to update across the board in the next couple of weeks.

**Comment by mhhplumber** [comment] 2022-11-30 23:07
@nashmrd 
try adding this annotation
`container.seccomp.security.alpha.kubernetes.io/system-probe: runtime/default`
what 3.1.9 fixes is allowing an additional syscall in the created seccomp profile, you can however just use a different profile

**Comment by igaskin** [comment] 2022-11-30 23:27
@nashmrd I too am using the datadog-operator, and was able to confirm that the configmap generated by the operator in chart version `0.9.1` does not include `faccessat` in the seccomp profile.  Curiously the operator code has included these changes, but it appears that haven't made it to a release.  
https://github.com/DataDog/datadog-operator/blob/main/controllers/datadogagent/component/agent/default.go#LL451C15-L451C15

I tested this operator image tag `0.8.3`, `1.0.0-rc3`, and latest, none of which corrected the configmap.
https://registry.hub.docker.com/r/datadog/operator/tags

At least for me, I'll be using the datadog agent helm chart instead of the datadog operator helm chart.

**Comment by gotchipete** [comment] 2023-01-20 22:02
> @nashmrd try adding this annotation `container.seccomp.security.alpha.kubernetes.io/system-probe: runtime/default` what 3.1.9 fixes is allowing an additional syscall in the created seccomp profile, you can however just use a different profile

This worked for me, I had
        `container.seccomp.security.alpha.kubernetes.io/system-probe: localhost/system-probe`
... once I replaced with 
        `container.seccomp.security.alpha.kubernetes.io/system-probe: runtime/default`
... smooth sailing!

**Comment by ishworg** [comment] 2023-02-16 09:38
helm chart 3.1.10 fixes the regression. 

but, on kernel `5.4.228-131.415.amzn2.x86_64`, we get a GP fault.

```
Feb 16 09:25:05 ip-10-250-19-90 kernel: ------------[ cut here ]------------
Feb 16 09:25:05 ip-10-250-19-90 kernel: General protection fault in user access. Non-canonical address?
Feb 16 09:25:05 ip-10-250-19-90 kernel: WARNING: CPU: 4 PID: 24530 at arch/x86/mm/extable.c:77 ex_handler_uaccess+0x4d/0x60
Feb 16 09:25:05 ip-10-250-19-90 kernel: Modules linked in: binfmt_misc xt_owner xt_REDIRECT xt_multiport veth xt_state xt_connmark nf_conntrack_netlink nfnetlink xt_addrtype xt_statistic xt_nat ipt_REJECT nf_reject_ipv4 ip_vs_sh ip_vs_wrr ip_vs_rr ip_vs iptable_mangle ip6table_mangle ip6table_filter ip6table_nat xt_MASQUERADE xt_conntrack xt_comment xt_mark iptable_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 iptable_filter bpfilter sunrpc crc32_pclmul ghash_clmulni_intel br_netfilter bridge aesni_intel stp ena llc mousedev crypto_simd overlay psmouse cryptd button evdev glue_helper crc32c_intel autofs4
Feb 16 09:25:05 ip-10-250-19-90 kernel: CPU: 4 PID: 24530 Comm: system-probe Not tainted 5.4.228-131.415.amzn2.x86_64 #1
Feb 16 09:25:05 ip-10-250-19-90 kernel: Hardware name: Amazon EC2 c5a.2xlarge/, BIOS 1.0 10/16/2017
Feb 16 09:25:05 ip-10-250-19-90 kernel: RIP: 0010:ex_handler_uaccess+0x4d/0x60
Feb 16 09:25:05 ip-10-250-19-90 kernel: Code: 83 c4 08 b8 01 00 00 00 5b c3 80 3d ad 92 75 01 00 75 dc 48 c7 c7 80 21 07 82 48 89 34 24 c6 05 99 92 75 01 01 e8 b3 ff 01 00 <0f> 0b 48 8b 34 24 eb bd 90 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44
Feb 16 09:25:05 ip-10-250-19-90 kernel: RSP: 0018:ffffc900022cfa08 EFLAGS: 00010282
Feb 16 09:25:05 ip-10-250-19-90 kernel: RAX: 0000000000000000 RBX: ffffffff81c045a0 RCX: 0000000000000000
Feb 16 09:25:05 ip-10-250-19-90 kernel: RDX: 0000000000000007 RSI: ffffffff82dd759f RDI: ffffffff82dd512c
Feb 16 09:25:05 ip-10-250-19-90 kernel: RBP: 000000000000000d R08: ffffffff82dd7560 R09: 000000000000003f
Feb 16 09:25:05 ip-10-250-19-90 kernel: R10: 0000000000000000 R11: 0000000000005fd2 R12: 0000000000000000
Feb 16 09:25:05 ip-10-250-19-90 kernel: R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
Feb 16 09:25:05 ip-10-250-19-90 kernel: FS:  00007f79f2f3e640(0000) GS:ffff888424100000(0000) knlGS:0000000000000000
Feb 16 09:25:05 ip-10-250-19-90 kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Feb 16 09:25:05 ip-10-250-19-90 kernel: CR2: 000000c000d6b000 CR3: 00000003a4404000 CR4: 00000000003406e0
Feb 16 09:25:05 ip-10-250-19-90 kernel: Call Trace:
Feb 16 09:25:05 ip-10-250-19-90 kernel: fixup_exception+0x43/0x60
Feb 16 09:25:05 ip-10-250-19-90 kernel: do_general_protection+0x46/0x140
Feb 16 09:25:05 ip-10-250-19-90 kernel: general_protection+0x28/0x30
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? copy_user_generic_string+0x31/0x40
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? __probe_kernel_read+0x54/0x80
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? tcp_getsockopt+0x5/0x30
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? bpf_probe_read+0x98/0xa0
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? tcp_getsockopt+0x5/0x30
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? trace_call_bpf+0x62/0xd0
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? tcp_getsockopt+0x1/0x30
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? tcp_getsockopt+0x1/0x30
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? tcp_getsockopt+0x5/0x30
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? kprobe_perf_func+0x201/0x280
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? tcp_getsockopt+0x1/0x30
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? tcp_getsockopt+0x5/0x30
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? kprobe_ftrace_handler+0x92/0xf0
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? ftrace_ops_assist_func+0x98/0x110
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? map_update_elem+0x1eb/0x390
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? 0xffffffffa00e50bf
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? do_tcp_getsockopt.isra.44+0xdd0/0xdd0
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? tcp_getsockopt+0x1/0x30
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? tcp_getsockopt+0x5/0x30
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? __sys_getsockopt+0xb0/0x120
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? __x64_sys_getsockopt+0x20/0x30
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? do_syscall_64+0x48/0xf0
Feb 16 09:25:05 ip-10-250-19-90 kernel: ? entry_SYSCALL_64_after_hwframe+0x5c/0xc1
Feb 16 09:25:05 ip-10-250-19-90 kernel: ---[ end trace 40123dadeae3f453 ]---
```

**Comment by ishworg** [comment] 2023-02-16 09:40
perhaps, there should be a guidance from ddog team on the helm chart on the kernel compatibility (version, changelogs etc)? i have seen dirty GP faults and panics in the past (the old days of eBPF instrumentation code in ddog agents) and fixed by manually bisecting kernel releases with the _then_ uptodate agents... room to improve.

**Comment by brycekahle** [comment] 2023-02-16 18:11
@ishworg That is a warning and logged once per boot. It is the result of the current kernel struct offset guessing logic, which walks addresses to find the correct offsets at runtime. This will no longer be a problem once all our eBPF-based products have transitioned to CO-RE or runtime compilation (currently in-progress, so hopefully within a couple versions).
