### ISSUE TITLE
Datadog reports lambda authorizer's 401 statusCode response as 503 or 502

### ISSUE THREAD

**Issue by akinboboye** [DataDog/datadog-agent#16351] opened 2023-03-29 21:12 UTC
At my organization, we are encountering a problem where the Lambda authorizer's 401 status code is being reported as either 502 or 503. Interestingly, API Gateway responds with the correct 401 status code, as confirmed through tests using Postman and other clients. We are currently unsure about the cause of this issue, but it is concerning because it gives the impression that there may be a problem with our Lambda authorizer.

Initially, we suspected that the issue could be related to the serverless-plugin-datadog or the datadog-lambda-js version, since we observed the following logs whenever a 401 status code was returned by the authorizer:

![Screenshot 2023-03-28 at 7 59 07 PM](https://user-images.githubusercontent.com/60622084/228669852-5e69a0a7-706c-4200-ba0a-e20f75863eaa.png)

However, after reviewing the solution to the issue provided [here](https://github.com/DataDog/datadog-agent/issues/14374), we continue to experience the same behavior, with the only difference being that the log messages from the extension have changed.
![image](https://user-images.githubusercontent.com/60622084/228670653-e5239da6-907d-4006-b974-60f92bfea80b.png)

I have made an effort to create a minimal implementation to reproduce the issue, in order to determine whether there is an issue with our configuration or to seek assistance in resolving it. The implementation can be found at [datadog-authorizer-issue](https://github.com/akinboboye/datadog-authorizer-issue). Please note that functioning AWS and Datadog accounts are required to use this implementation.

If you are unable to review the link, I have included the most crucial parts of the code below for your convenience:

**.env**
```txt
DATADOG_API_KEY=<your dd api key>
SHOULD_AUTHORIZE_REQUEST=false
```
**serverless.ts**
``` typescript
import { AWS } from '@serverless/typescript';

const configuration: AWS = {
  service: 'datadog',
  useDotenv: true,
  provider: {
    name: 'aws',
    runtime: 'nodejs18.x',
    timeout: 30,
    stage: 'test',
  },
  package: { individually: true },
  functions: {
    authorizer: {
      handler: 'dist/authorizer.handler',
      architecture: 'arm64',
      environment: {
        SHOULD_AUTHORIZE_REQUEST: '${env:SHOULD_AUTHORIZE_REQUEST}'
      },
      package: {
        patterns: ['!./**', 'dist/authorizer.js']
      }
    },
    getUsers: {
      handler: 'dist/get-user.handler',
      architecture: 'arm64',
      events: [
        {
          http: {
            method: 'get',
            path: '/',
            authorizer:  {
              name: 'authorizer',
              resultTtlInSeconds: 0,
              type: 'request',
            },
            cors: true,
          },
        },
      ],
      package: {
        patterns: ['!./**', 'dist/get-user.js']
      }
    },
  },
  plugins: ['serverless-plugin-datadog', 'serverless-offline', 'serverless-plugin-lambda-insights'],
  custom: {
    datadog: {
      enableXrayTracing: true,
      addLayers: true,
      apiKey: '${env:DATADOG_API_KEY}',
      env: 'test',
    },
    lambdaInsights: {
      defaultLambdaInsights: true,
    },
  }
}

module.exports = configuration;
```
**package.json**
```json
{
  "name": "datadog-authorizer-issue",
  "version": "1.0.0",
  "main": "index.js",
  "repository": "git@github.com:akinboboye/datadog-authorizer-issue.git",
  "license": "MIT",
  "scripts": {
    "compile": "tsc",
    "deploy": "yarn compile && ./node_modules/.bin/sls deploy",
    "start:local": "yarn compile && node --inspect ./node_modules/.bin/sls offline"
  },
  "devDependencies": {
    "@serverless/typescript": "^3.29.0",
    "@types/aws-lambda": "^8.10.114",
    "@types/node": "^18.15.11",
    "aws-lambda": "^1.0.7",
    "serverless": "^3.29.0",
    "serverless-offline": "^12.0.4",
    "serverless-plugin-datadog": "^5.21.0",
    "serverless-plugin-lambda-insights": "^1.6.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.0.2"
  },
  "dependencies": {
    "datadog-lambda-js": "^6.87.0"
  }
}
```

***authorizer.ts***
```typescript
import {
  APIGatewayRequestAuthorizerEvent,
  APIGatewayAuthorizerResult
} from 'aws-lambda';
import { datadog } from 'datadog-lambda-js';

const authorizer = async (
  event: APIGatewayRequestAuthorizerEvent
): Promise<APIGatewayAuthorizerResult> => {
  const shouldAuthorizeRequest =
    process.env.SHOULD_AUTHORIZE_REQUEST?.toLowerCase() === 'true'

  if (!shouldAuthorizeRequest) {
    throw new Error("Unauthorized");
  }

  return {
    policyDocument: {
      Version: '2012-10-17',
      Statement: [{
        Action: 'execute-api:Invoke',
        Effect: 'Allow',
        Resource: '*'
      }],
    },
    principalId: 'user'
  }
};

export const handler = datadog(authorizer);
```

**get-user.ts**
```typescript
import { 
  APIGatewayProxyStructuredResultV2, 
  APIGatewayEvent,
} from 'aws-lambda';

import { datadog } from "datadog-lambda-js";

const getUser = async (
  event: APIGatewayEvent
  ): Promise<APIGatewayProxyStructuredResultV2> => {
  return {
    statusCode: 200,
    headers: {
      'Access-Control-Allow-Headers': '*',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': '*',
    },
    body: JSON.stringify({
      message: 'get user handler response',
    }),
  };
};

export const handler = datadog(getUser);
```

Thank you for reading or taking a look. 🙏

**Comment by akinboboye** [comment] 2023-04-03 20:40
Did I submit this incorrectly? If so, could someone assist me in doing it the proper way?

**Comment by akinboboye** [comment] 2023-04-04 14:26
Thank you @astuyve  for taking a look. See the expanded error below:

![image](https://user-images.githubusercontent.com/60622084/229823692-14931e27-f31e-4cc4-93ac-b906cfdeab91.png)


Even though these errors are thrown, they are understood by APIGateway and reported as 401.

**Comment by astuyve** [comment] 2023-04-04 16:17
I see - thanks for the context!

It's true that a Lambda-based custom Authorizer which throws an unhandled exception will result in a 401 status code being returned to the user by API Gateway, but as far as I can tell from the docs, this isn't the intentional way to return a 401 status code to the user from API Gateway.

This seems to be a side effect of the API Gateway + Lambda-based Custom Authorizer system designed to fail closed (eg - not permitting access if a function throws an unhandled error, and not leaking information to the calling user).

For token-based authorizers, returning the string "unauthorized" via callback is recommended [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html) in the docs.

For request type authorizers, returning "unauthorized", or an empty string via the "Effect" key in the JSON response is recommended. (Same docs as above):
<img width="2103" alt="image" src="https://user-images.githubusercontent.com/1598537/229850534-65f20ee1-dc70-4dad-8920-e31d8af07e31.png">

"Deny" will return a 403 status code (eg: the user provided an authentication token, but it was not valid for the requested resource).

As far as I can tell, there's no documentation suggesting developers throw unhandled errors to respond with 401 status codes. I apologize in advance if I'm mistaken here, as that's also a definite possibility.

This brings us to Datadog. Today I don't expect that we'll catch these errors and determine that a function is in fact an authorizer, which is throwing an unhandled error in an attempt to return a 401. Our tracers detect unhandled exceptions as an error and mark it as such. API Gateway decides to convert that to the user, so as to not leak information to a potential attacker (eg: this function panicked with that input).

As an aside: you can also save money on Lambda by rejecting requests with no authorization header (eg: 401) using a [custom response mapping](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-gatewayResponse-definition.html), which I believe is considered best practice, but likely not used frequently.

Please let me know if you've got any other questions, thank you!

**Comment by akinboboye** [comment] 2023-04-04 16:29
thanks for looking @astuyve! What's funny is that using the callback style also results in the same effect. Basically a call up the stack throws an error, we handle that error and then pass `Unauthorized` to the callback. DD still reports it as 502 or 503.

**Comment by astuyve** [comment] 2023-04-04 17:28
Hey @akinboboye - I don't have a reproduction case with that on hand, but if you could update your repo with a case I can definitely look into it.

**Comment by akinboboye** [comment] 2023-04-06 17:08
@astuyve I have updated the repo. The authorizer now uses the callback style to return unauthorized. https://github.com/akinboboye/datadog-authorizer-issue/blob/main/src/authorizer.ts

**Comment by joeyzhao2018** [comment] 2023-04-11 18:56
Hi @akinboboye , thank you for updating the example. However, I think this is still expected behavior. 
If you remove all the Datadog instrumentation in this case, it's still treated as an error by the lambda runtime ( or the `callback` to be precise).  Therefore Datadog layer doesn't make any modification and behave the same.

To avoid such errors, we would recommend avoid the `unauthorized` path and instead use
```
export const handler =  function(event, context, callback) {
    var token = event.authorizationToken;
    switch (token) {
        case 'allow':
            callback(null, generatePolicy('user', 'Allow', event.methodArn));
            break;
        case 'deny':
            callback(null, generatePolicy('user', 'Deny', event.methodArn));
            break;
        default:
            callback("Error: Invalid token"); // Return a 500 Invalid token response
    }
};
``` 
as the AWS documentation is somewhat misleading regarding 401 information.
Please let us know if you have further questions.

**Comment by joeyzhao2018** [comment] 2023-04-12 23:34
Hi @akinboboye, you are right they did return 401 response code. However, when I tested with Datadog layers it's also returning 401. 
<img width="912" alt="Screenshot 2023-04-12 at 7 23 53 PM" src="https://user-images.githubusercontent.com/5253430/231607278-ec6f1993-a177-4a8b-9110-ac42636ad21f.png">

With that being said, I was about to reproduce the `Runtime.UnhandledPromiseRejection` and you are right this is not intended behavior. (Thank you for providing the replicable test case again).
I was about to fix that by changing the `authorizer.ts` file.  line 6 `import { datadog } from 'datadog-lambda-js';` should be removed and the last line should be `export const handler = authorizer;`. 
This is because the handler function is already wrapped by the Datadog-Node18-x layer. Wrapping it again can cause unexpected behaviors. 

Please let me know if this fixes your issue. In short, I don't think we are altering the response in anyway in the unauthorized case.

**Comment by MatthiasVanMeerbeek** [comment] 2023-10-30 14:42
Hi, I don't really understand the last message by @joeyzhao2018. 

I'm encountering the same issue in my project. When [datadog-lambda-js](https://github.com/DataDog/datadog-lambda-js) is enabled the errors are returned as 500 internal server error. When it is disabled, everything works as expected (except for the tracing in Datadog).
I'm not importing `datadog` from `datadog-lambda-js` and I'm also not encapsulating my handler with `datadog()`, I'm directly exporting my handler.

So from my understanding the issue is in the "datadog-lambda-js" library. Is an issue logged in [datadog-lambda-js](https://github.com/DataDog/datadog-lambda-js)? Or is it enough that this issue is open under [datadog-agent](https://github.com/DataDog/datadog-agent)?

**Comment by astuyve** [comment] 2023-10-30 14:56
Hi @MatthiasVanMeerbeek, thanks for reaching out.

This issue is quite old and I believe the root cause to the [unhandled promise rejection](https://github.com/DataDog/datadog-agent/issues/16351#issuecomment-1496069978) error was ultimate fixed [here](https://github.com/DataDog/dd-trace-js/pull/3278), where throwing a custom error message w/ code ultimately resulted in an unhandled promise rejection error in ddtrace.

If this error is still occurring for you, please open an issue in [datadog lambda js](https://github.com/DataDog/datadog-lambda-js) with detailed steps on how you can reproduce it (ideally with sample code or a small sample repo like above), as well as a detailed summary of which version of the software you're using.

I'm going to close this issue as it's unrelated to the datadog agent.

Thanks!

**Closed by astuyve** 2023-10-30 14:56 UTC
Labels: team/serverless
