### ISSUE TITLE
 Error while processing transaction: error while sending transaction

### ISSUE THREAD

**Issue by urosgruber** [DataDog/datadog-agent#1546] opened 2018-03-30 18:15 UTC
I was able to build agent from master. After running `./bin/agent/agent start -c ./bin/agent/dist/` I'm getting weird following error message 
```
2018-03-30 19:57:38 CEST | ERROR | (worker.go:135 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post https://6-0-0-app.agent.datadoghq.com/api/v1/check_run?api_key=*************************54d58: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

There is also no connection visible on dashboard. One other thing is version 
`Agent 6.0.0 - Commit:  - Serialization version:` but master is on 6.1.1.

Anyone can help here debug what is going on.

**Comment by arbll** [comment] 2018-03-30 19:19
Hi @urosgruber!

The version is given at compile time by the build script using the last git tag. `6.0.0` probably correspond to the default value for the version : https://github.com/DataDog/datadog-agent/blob/1b60603ab8a5b50b644d8a73d143e519daf127bd/pkg/version/base.go#L16

First thing on top of my head : did you clone the repository or downloaded a zip ?

If you did indeed clone the repo could you tell me how you compiled the agent ?

Thanks!

**Comment by urosgruber** [comment] 2018-03-30 20:01
I cloned it and then 
`invoke deps` and `invoke agent.build --build-include=log, process`

**Comment by urosgruber** [comment] 2018-04-15 18:56
Anything new around here? I can run some debugging if it helps?

**Comment by truthbk** [comment] 2018-05-15 19:43
@urosgruber as far as your the log message you're seeing that looks like there was some kind of networking issue preventing the transactions (payloads) from being pushed to datadog at certain times. The forwarder, once the transaction fails re-enqueues it and is attempted later.

Are the errors in the log intermittent?

Could you please submit a flare to the support team so we can take a look at the logs and try to decide if this is indeed just a networking issue? 

Thanks!

**Comment by urosgruber** [comment] 2018-05-16 18:30
@truthbk I've manage to build `agent` manually but on the latest 6.2. Agent connects successfully and data is also visible on DD dashboard. Not sure if the issue was fixed with latest version or it was just develop build that cause this problem. I'll check if 6.2 develop build also have similar issue.

**Comment by urosgruber** [comment] 2018-05-18 18:10
@arbll I think error is now gone with 6.2.x Nothing was changed except I did pull from git and build with same command.

**Comment by karthikdialpad** [comment] 2019-05-09 11:55
I am facing the same issue in kubernetes environment, below is the error message
I am using 6.10.1 version of datadog-agent image

{"log":"[ AGENT ] 2019-05-09 11:46:47 UTC | ERROR | (pkg/forwarder/worker.go:142 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post https://6-10-1-app.agent.datadoghq.com/api/v1/check_run?api_key=****************}: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\n","stream":"stdout","time":"2019-05-09T11:46:47.771863625Z"}

I tried to send the flare but I am getting the error
Error: Post https://6-10-1-flare.agent.datadoghq.com/support/flare?api_key=***********************}: dial tcp: lookup 6-10-1-flare.agent.datadoghq.com: Temporary failure in name resolution

**Comment by Le0exxx** [comment] 2019-08-02 02:51
I have the same error as well, I am using the latest docker image and pure docker launch like below,

docker run -d --name dd-agent -v /var/run/docker.sock:/var/run/docker.sock:ro                               -v /proc/:/host/proc/:ro                               -v /cgroup/:/host/sys/fs/cgroup:ro                               -e DD_API_KEY=xxxxx                   datadog/agent:latest



2019-08-02 02:37:50 UTC | CORE | ERROR | (pkg/forwarder/worker.go:142 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post https://6-13-0-app.agent.datadoghq.com/intake/?api_key=*************************: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by joaquin386** [comment] 2019-08-05 10:53
I try to deploy datadog/agent-jmx:latest to AWS ECS fargate and keep getting the following errors:
- Error submitting payload to https://process.datadoghq.com/api/v1/collector: Post https://process.datadoghq.com/api/v1/collector: read tcp 10.0.10.10:39536->52.207.126.249:443: read: connection reset by peer
- TLS Handshake failure: read tcp 10.0.10.10.33:57718->52.45.28.194:443: read: connection reset by peer
- Too many errors for endpoint 'https://6-13-0-app.agent.datadoghq.com/api/v1/series?api_key=******************************': retrying later
Is there anything special that needs to be done to deploy datadog docker container into that ECS Cluster (fargate)?

**Comment by ocervell** [comment] 2020-10-02 14:17
Getting the same issue on Google Kubernetes Engine, any idea what might be the cause ?

**Comment by ameyapanse** [comment] 2020-11-18 10:11
@joaquin386 @ocervell Were you able to fix this ? I'm getting the same errors on ECS (EC2).

**Comment by thiagolsfortunato** [comment] 2021-03-10 15:24
Any news?

**Comment by windingroad100hf** [comment] 2021-05-17 18:47
@ocervell We're seeing this in our Kubernetes clusters as well. Were you able to fix this? We get the following error, which originates in [worker.go](https://github.com/DataDog/datadog-agent/blob/140a4ee164261ef2245340c50371ba989fbeb038/pkg/forwarder/worker.go#L179) not the [domain_forwarder.go](https://github.com/DataDog/datadog-agent/blob/master/pkg/forwarder/domain_forwarder.go#L110). If other users are seeing similar logs, then it looks like this may be a problem with the retry routine itself (or at least how users have it configured).

`2021-05-17 17:55:25 UTC | PROCESS | ERROR | (pkg/forwarder/worker.go:174 in process) | Too many errors for endpoint 'https://process.datadoghq.com/api/v1/container': retrying later
2021-05-17 17:55:36 UTC | PROCESS | ERROR | (pkg/forwarder/domain_forwarder.go:133 in retryTransactions) | Dropped 3 transactions in this retry attempt: 0 for exceeding the retry queue payloads size limit of 15728640, 3 because the workers are too busy`

**Comment by huy-hoang-mox** [comment] 2021-05-18 06:50
I also face the same issue: 
`2021-05-11 22:51:00 UTC | PROCESS | ERROR | (pkg/forwarder/worker.go:178 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post "https://orchestrator.datadoghq.com/api/v1/orchestrator": EOF`

**Comment by PHameete** [comment] 2021-07-15 09:30
Same issue here. Datadog agent version 7.28.1 on AWS EKS 1.19.8

```
Error while processing transaction: error while sending transaction, rescheduling it: Post "https://orchestrator.datadoghq.com/api/v1/orchestrator": EOF
```

**Comment by sdy15** [comment] 2021-07-15 12:18
I am facing the same issue in Datadog agent version 7.29.0.Sent the flare to support.
>
TC | CORE | ERROR | (pkg/forwarder/worker.go:179 in process) | Too many errors for endpoint 'https://7-29-0-app.agent.datadoghq.com/api/v1/series?api_key=***************************eb3c3': retrying later
>

**Comment by ianhundere** [comment] 2021-10-04 20:42
same issue here:
```
2021-10-04 20:39:52 UTC | PROCESS | ERROR | (pkg/forwarder/worker.go:183 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post "https://orchestrator.datadoghq.com/api/v1/orchestrator": EOF
```

**Comment by TwistedLogic** [comment] 2021-10-05 08:57
Same issue here:
```
2021-10-04 16:35:33 UTC | SAGENT | ERROR | SyncForwarder.sendHTTPTransactions final attempt: error while sending transaction, rescheduling it: Post "https://6-0-0-app.agent.datadoghq.eu/api/v1/check_run?api_key=***************************77453": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2021-10-05 00:36:29 UTC | SAGENT | ERROR | SyncForwarder.sendHTTPTransactions final attempt: error while sending transaction, rescheduling it: Post "https://6-0-0-app.agent.datadoghq.eu/api/beta/sketches?api_key=***************************77453": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
I'm using the Datadag Lambda Extension installed using the Datadog Serverless Plugin, and having a few errors like those.

**Comment by davidlbyrne** [comment] 2021-10-06 00:17
same issue here, I think something is wrong with their API and they dont want to surface it. 
```
2021-10-04T14:37:20.259-07:00
2021-10-04 21:37:20 UTC | SAGENT | ERROR | SyncForwarder.sendHTTPTransactions final attempt: error while sending transaction, rescheduling it: Post "https://6-0-0-app.agent.datadoghq.com/api/v1/series?api_key=***************************5ccc2": dial tcp 3.233.149.59:443: i/o timeout
```

**Comment by kaypeter87** [comment] 2021-11-22 18:35
We are also running into an issue with the `sidecar` container for the `datadog-agent` and getting the following errors:

```
2021-11-22 18:26:28 UTC | CORE | ERROR | (pkg/forwarder/worker.go:179 in process) | Too many errors for endpoint 'https://*-**-*-app.agent.datadoghq.com/api/v1/check_run?api_key=***************************': retrying later
```

Are there any updates to this issue? It is causing confusion with our logs in ECS.

**Comment by Suchit8** [comment] 2021-12-08 09:48
A number of my datadog agents are working fine but a few new installations and the agents which were restarted recently facing similar issues. Error logs attached.

`2021-12-08 04:33:18 EST | CORE | ERROR | (pkg/forwarder/transaction/transaction.go:108 in func4) | TLS Handshake failure: net/http: TLS handshake timeout
2021-12-08 04:33:18 EST | CORE | ERROR | (pkg/forwarder/worker.go:183 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post "https://7-32-1-app.agent.datadoghq.com/intake/?api_key=***************************456ed": net/http: TLS handshake timeout
`

**Comment by djmitche** [comment] 2021-12-13 14:56
It looks like this issue has become a bit of a random collection of connection issues (and some build issues).

In general, DataDog support is best suited to handle these situations: they can look at the circumstances, examine a flare, and make recommendations for the most successful configurations.  I'll close this issue up now.

**Closed by djmitche** 2021-12-13 14:56 UTC

**Comment by PHameete** [comment] 2021-12-13 15:33
@djmitche I've frequently contacted support about such issues, but after the initial generic reply they do not get back to me.

**Comment by PHameete** [comment] 2021-12-13 15:34
@djmitche I've frequently contacted support about such issues, but after the initial generic reply they do not get back to me.

**Comment by ianhundere** [comment] 2022-01-05 15:09
i updated/increased my `resources` for all of the agents and i'm no longer getting this error.

**Comment by ianhundere** [comment] 2022-01-05 18:52
reacgi

> In general, DataDog support is best suited to handle these situations: they can look at the circumstances, examine a flare, and make recommendations for the most successful configurations. I'll close this issue up now.

reaching out now :)

**Comment by ianhundere** [comment] 2022-01-07 20:26
and the response

"Thank you for verifying. I have confirmed with our engineers that this is a known issue that is being tracked. I will mark this as closed for now, but feel free to reach back out to Support if you have any questions on this. Thank you for helping us to improve our product!"

so maybe this issue should be opened back up considering it's a known issue being tracked internally ?

**Comment by ianhundere** [comment] 2022-01-07 20:27
@djmitche  and the response

"Thank you for verifying. I have confirmed with our engineers that this is a known issue that is being tracked. I will mark this as closed for now, but feel free to reach back out to Support if you have any questions on this. Thank you for helping us to improve our product!"

so maybe this issue should be opened back up considering it's a known issue being tracked internally ?

**Comment by djmitche** [comment] 2022-01-07 21:21
As I mentioned, this has become a bit of a "collector" issue for a bunch of different problems with similar error messages.  I think the internal tracking will be sufficient, and there's no need to re-open this issue.

**Comment by ianhundere** [comment] 2022-01-07 21:24
ah, thanks for clarifying. we'll ignore these logs for now.

**Comment by ianhundere** [comment] 2022-01-10 14:15
@djmitche could you provide some open issues that mirror these logs?

**Comment by vsaldivia** [comment] 2022-02-01 14:59
![image](https://user-images.githubusercontent.com/22179835/151992579-caf33cec-d8ba-4592-ba5d-beec6fcba840.png)

Check the API KEY!!

**Comment by denbon05** [comment] 2022-11-08 21:38
![image](https://user-images.githubusercontent.com/58662935/200680791-cfcc5bdb-4062-4b7c-9cb6-6929183bacc2.png)
![image](https://user-images.githubusercontent.com/58662935/200681109-cfa24c8f-c000-416e-a778-eb3bec7f82c9.png)
Still error

**Comment by nmahavad** [comment] 2023-03-20 18:21
> ![image](https://user-images.githubusercontent.com/58662935/200680791-cfcc5bdb-4062-4b7c-9cb6-6929183bacc2.png) ![image](https://user-images.githubusercontent.com/58662935/200681109-cfa24c8f-c000-416e-a778-eb3bec7f82c9.png) Still error

i am following this ..

**Comment by rossigee** [comment] 2023-09-10 01:48
**Too many errors for endpoint** is perhaps one of the worst error messages I've come across in recent times. It is useless, confusing and causes massive issue report threads like this.

The required action here seems pretty clear to me. Datadog engineering team need to fix the error handling to provide a bit more information. That would save the Datadog support team, me and all these other users in the above thread and related threads a whole bunch of time and headaches!

**Comment by rossigee** [comment] 2023-09-10 01:54
So, it seems the error indicates that a 'circuit breaker' has considered your target host to be on a blacklist/blockedList... :thinking:

```
	// Run the endpoint through our blockedEndpoints circuit breaker
	target := t.GetTarget()
	if w.blockedList.isBlock(target) {
		requeue()
		log.Errorf("Too many errors for endpoint '%s': retrying later", target)
	} else if err := t.Process(ctx, w.Client); err != nil {
		w.blockedList.close(target)
		requeue()
		log.Errorf("Error while processing transaction: %v", err)
	} else {
		w.blockedList.recover(target)
	}
```

**Comment by rossigee** [comment] 2023-09-10 01:57
(sorry for the noise, I just realised I posted the above comments on an unrelated issue report! :facepalm:)

**Comment by sunshuaidong** [comment] 2025-03-31 06:50
我也遇到同样的问题,我已经解决了,我使用docker拉起datadog-agent容器时,容器内部无法访问外部网络在启动脚本中添加 
--network host 问题得到了解决
