### ISSUE TITLE
 Can't access the cAdvisor metrics if kubelet runs with --cadvisor-port=0

### ISSUE THREAD

**Issue by stamak** [DataDog/datadog-agent#975] opened 2017-12-20 14:59 UTC
**Output of the info page (if this is a bug)**
```
# kubectl exec  dd-agent-72ft2 /etc/init.d/datadog-agent status
Warning: Known bug in Linux Kernel 3.18+ causes 'status' to fail.
Calling 'info', instead...
====================
Collector (v 5.20.2)
====================

  Status date: 2017-12-20 14:49:08 (9s ago)
  Pid: 28
  Platform: Linux-4.13.16-coreos-r1-x86_64-with-debian-8.10
  Python Version: 2.7.14, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======

    NTP offset: -0.004 s
    System UTC time: 2017-12-20 14:49:18.056326

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d
  Hostnames
  =========

    socket-hostname: dd-agent-72ft2
    local-hostname: k8s-node0-cdx-dev-k8s-ams1.novalocal
    public-hostname: k8s-node0-cdx-dev-k8s-ams1.novalocal
    public-ipv4: 159.117.203.77
    hostname: k8s-node0-cdx-dev-k8s-ams1.novalocal
    socket-fqdn: dd-agent-72ft2

  Checks
  ======

    etcd (5.20.2)
    -------------
      - Collected 0 metrics, 0 events & 0 service checks

    kubernetes (5.20.2)
    -------------------
      - instance #0 [WARNING]
          Warning: Can't access the cAdvisor metrics, performance metrics and limits/requests will not be collected. Please setup your
 kubelet with the --cadvisor-port=4194 option, or set port to 0 in this check's configuration to disable cAdvisor lookup.
      - Collected 3 metrics, 0 events & 3 service checks

    ntp (5.20.2)
    ------------
      - Collected 0 metrics, 0 events & 0 service checks

    disk (5.20.2)
    -------------
      - instance #0 [OK]
      - Collected 32 metrics, 0 events & 0 service checks
    docker_daemon (5.20.2)
    ----------------------
      - instance #0 [OK]
      - Collected 118 metrics, 0 events & 1 service check


  Emitters
  ========

    - http_emitter [OK]

====================
Dogstatsd (v 5.20.2)
====================

  Status date: 2017-12-20 14:49:17 (3s ago)
  Pid: 20
  Platform: Linux-4.13.16-coreos-r1-x86_64-with-debian-8.10
  Python Version: 2.7.14, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log

  Flush count: 119
  Packet Count: 1667
  Packets per second: 1.2
  Metric count: 13
  Event count: 0
  Service check count: 0

====================
Forwarder (v 5.20.2)
====================

  Status date: 2017-12-20 14:49:19 (3s ago)
  Pid: 19
  Platform: Linux-4.13.16-coreos-r1-x86_64-with-debian-8.10
  Python Version: 2.7.14, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log

  Queue Size: 0 bytes
  Queue Length: 0
  Flush Count: 393
  Transactions received: 302
  Transactions flushed: 302
  Transactions rejected: 0
  API Key Status: API Key is valid


======================
Trace Agent (v 5.20.2)
======================

  Pid: 18
  Uptime: 1239 seconds
  Mem alloc: 3234128 bytes

  Hostname: dd-agent-72ft2
  Receiver: 0.0.0.0:8126
  API Endpoint: https://trace.agent.datadoghq.com


  Bytes sent (1 min): 0
  Traces sent (1 min): 0
  Stats sent (1 min): 0
```

**Describe what happened:**

I have       

```
- instance #0 [WARNING]
          Warning: Can't access the cAdvisor metrics, performance metrics and limits/requests will not be collected. Please setup your
 kubelet with the --cadvisor-port=4194 option, or set port to 0 in this check's configuration to disable cAdvisor lookup.
      - Collected 3 metrics, 0 events & 3 service checks
```

**Describe what you expected:**

no

```
      - instance #0 [WARNING]
          Warning: Can't access the cAdvisor metrics, performance metrics and limits/requests will not be collected. Please setup your
 kubelet with the --cadvisor-port=4194 option, or set port to 0 in this check's configuration to disable cAdvisor lookup.
      - Collected 3 metrics, 0 events & 3 service checks
```

when kubelet runs with param *--cadvisor-port=0*

**Steps to reproduce the issue:**

Root cause is  running kubelet with parameter *--cadvisor-port=0*

*kubernetes* works fine with  *--cadvisor-port=0* but dd-agent does not

Once I have removed parameter *--cadvisor-port=0*
I do not have such problem
```
    kubernetes (5.20.2)
    -------------------
      - instance #0 [OK]
      - Collected 56 metrics, 77 events & 3 service checks
```

**Comment by stamak** [comment] 2017-12-20 15:13
Is there any way to disable cadvisor in dd-agent on k8s ?

**Comment by xvello** [comment] 2017-12-20 15:17
Hi @stamak ,

I am closing this issue as `invalid` because this repository is the one for the new agent6 codebase. This issue should have been filled on our [integrations-core](https://github.com/DataDog/integrations-core) repo.

The integration works as intended though, as cadvisor connectivity is required to retrieve cadvisor metrics. As the warning message instructs you, you can either enable the cadvisor port, or `set port to 0 in this check's configuration to disable cAdvisor lookup`.

If you need assistance in configuring the kubernetes check, feel free to contact [our support team](https://www.datadoghq.com/support/}

**Closed by xvello** 2017-12-20 15:17 UTC

**Comment by stamak** [comment] 2017-12-20 18:42
I saw that it is possible to do it in config file but I do not see any way to pass it to container via kubernetes yaml 
@xvello could you help if I am mistaken?
