### ISSUE TITLE
pkg/secrets: race condition found by TestExecCommandError

### ISSUE THREAD

**Issue by katiehockman** [DataDog/datadog-agent#19811] opened 2023-09-28 15:27 UTC
I'm seeing a flaky race in `pkg/secrets`. The link below is from a failed run in a PR that didn't touch this package in any way.

https://github.com/DataDog/datadog-agent/actions/runs/6318671427/job/17158161612?pr=19725

```
=== Failed
=== FAIL: pkg/secrets  (0.00s)
ERROR rerun aborted because previous run had a suspected panic and some test may not have run
panic: test timed out after 3m0s
running tests:
	TestExecCommandError (1m23s)
	TestExecCommandError/input (8s)

goroutine 68 [running]:
testing.(*M).startAlarm.func1()
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/testing/testing.go:2241 +0x3c5
created by time.goFunc
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 3 minutes]:
testing.(*T).Run(0xc0004cc4e0, {0x9c7e59?, 0x344333?}, 0xa05828)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/testing/testing.go:1630 +0x405
testing.runTests.func1(0xe9eb00?)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/testing/testing.go:2036 +0x45
testing.tRunner(0xc0004cc4e0, 0xc000263c08)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/testing/testing.go:1576 +0x10b
testing.runTests(0xc000222000?, {0xe[918](https://github.com/DataDog/datadog-agent/actions/runs/6318671427/job/17158161612?pr=19725#step:7:919)40, 0x1a, 0x1a}, {0x2ebe60?, 0xc000263ca8?, 0xe9e1a0?})
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc000222000)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/testing/testing.go:1906 +0x63a
github.com/DataDog/datadog-agent/pkg/secrets.TestMain(0x9beaa6?)
	D:/a/datadog-agent/datadog-agent/pkg/secrets/fetch_secret_test.go:50 +0x157
main.main()
	_testmain.go:130 +0x1ef

goroutine 19 [sync.Cond.Wait, 3 minutes]:
sync.runtime_notifyListWait(0xc0000d4650, 0x0)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/runtime/sema.go:527 +0x14f
sync.(*Cond).Wait(0x0?)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/sync/cond.go:70 +0x8c
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc00010e000)
	C:/Users/runneradmin/go/pkg/mod/github.com/cihub/seelog@v0.0.0-20151216151435-d2c6e5aa9fbf/behavior_asynclooplogger.go:50 +0xa5
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc00010e000)
	C:/Users/runneradmin/go/pkg/mod/github.com/cihub/seelog@v0.0.0-20151216151435-d2c6e5aa9fbf/behavior_asynclooplogger.go:63 +0x35
created by github.com/cihub/seelog.NewAsyncLoopLogger
	C:/Users/runneradmin/go/pkg/mod/github.com/cihub/seelog@v0.0.0-20151216151435-d2c6e5aa9fbf/behavior_asynclooplogger.go:40 +0xca

goroutine 20 [sync.Cond.Wait, 3 minutes]:
sync.runtime_notifyListWait(0xc0000d47d0, 0x0)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/runtime/sema.go:527 +0x14f
sync.(*Cond).Wait(0x0?)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/sync/cond.go:70 +0x8c
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc00010e120)
	C:/Users/runneradmin/go/pkg/mod/github.com/cihub/seelog@v0.0.0-20151216151435-d2c6e5aa9fbf/behavior_asynclooplogger.go:50 +0xa5
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc00010e120)
	C:/Users/runneradmin/go/pkg/mod/github.com/cihub/seelog@v0.0.0-20151216151435-d2c6e5aa9fbf/behavior_asynclooplogger.go:63 +0x35
created by github.com/cihub/seelog.NewAsyncLoopLogger
	C:/Users/runneradmin/go/pkg/mod/github.com/cihub/seelog@v0.0.0-20151216151435-d2c6e5aa9fbf/behavior_asynclooplogger.go:40 +0xca

goroutine 67 [syscall, 1 minutes, locked to thread]:
syscall.SyscallN(0x7ff88f813ef0?, {0xc0003fbc60?, 0x3?, 0x0?})
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/runtime/syscall_windows.go:557 +0x109
syscall.Syscall(0xc?, 0x2b?, 0xc0003c9400?, 0xc00020ce00?, 0x100c0003e0180?)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/runtime/syscall_windows.go:495 +0x3b
syscall.WaitForSingleObject(0xc0003ff2b0?, 0xffffffff)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/syscall/zsyscall_windows.go:1145 +0x65
os.(*Process).wait(0xc00040c960)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/os/exec_windows.go:18 +0x65
os.(*Process).Wait(...)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/os/exec.go:132
os/exec.(*Cmd).Wait(0xc000220c60)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/os/exec/exec.go:890 +0x45
os/exec.(*Cmd).Run(0x9c1691?)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/os/exec/exec.go:590 +0x39
github.com/DataDog/datadog-agent/pkg/secrets.setCorrectRight({0xc00021d710?, 0x9c61fe?})
	D:/a/datadog-agent/datadog-agent/pkg/secrets/check_rights_windows_test.go:27 +0x16a
github.com/DataDog/datadog-agent/pkg/secrets.TestExecCommandError.func6(0xc00005d520)
	D:/a/datadog-agent/datadog-agent/pkg/secrets/fetch_secret_test.go:137 +0x90
testing.tRunner(0xc00005d520, 0xc00008e900)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/testing/testing.go:1629 +0x3ea

goroutine 50 [chan receive, 1 minutes]:
testing.(*T).Run(0xc00005da00, {0x9beb96?, 0x2a2b6ae92f4?}, 0xc00008e900)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/testing/testing.go:1630 +0x405
github.com/DataDog/datadog-agent/pkg/secrets.TestExecCommandError(0xc00005d520?)
	D:/a/datadog-agent/datadog-agent/pkg/secrets/fetch_secret_test.go:134 +0x1ad
testing.tRunner(0xc00005da00, 0xa05828)
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/testing/testing.go:1629 +0x3ea
FAIL	github.com/DataDog/datadog-agent/pkg/secrets	187.843s

=== FAIL: pkg/secrets TestExecCommandError (unknown)
--- PASS: TestExecCommandError/Empty_secretBackendCommand (0.00s)
error: secret_backend_command stderr: 
--- PASS: TestExecCommandError/timeout (20.02s)
--- PASS: TestExecCommandError/No_Error (18.72s)
error: secret_backend_command stderr: 
--- PASS: TestExecCommandError/Error_returned (18.46s)
error: secret_backend_command stderr: 
--- PASS: TestExecCommandError/argument (18.21s)
	github.com/DataDog/datadog-agent/pkg/secrets	coverage: 29.4% of statements

=== FAIL: pkg/secrets TestExecCommandError/input (unknown)
	github.com/DataDog/datadog-agent/pkg/secrets	coverage: 29.4% of statements
```

**Comment by vickenty** [comment] 2023-10-03 09:38
This is believed to be caused by [slowness in powershell](https://github.com/actions/runner-images/issues/8380#issuecomment-1736788095), now fixed.

**Closed by vickenty** 2023-10-03 09:38 UTC
Labels: team/triage
