### ISSUE TITLE
json log file processing timestamps not processed?

### ISSUE THREAD

**Issue by bkruger99** [DataDog/datadog-agent#3926] opened 2019-07-24 20:32 UTC
**Output of the info page (if this is a bug)**
```
===============
Agent (v6.13.0)
===============

  Status date: 2019-07-24 20:15:00.986795 UTC
  Agent start: 2019-07-24 18:54:50.705497 UTC
  Pid: 10939
  Go Version: go1.11.5
  Python Version: 2.7.16
  Check Runners: 4
  Log Level: DEBUG

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -1.322ms
    System UTC time: 2019-07-24 20:15:00.986795 UTC

  Host Info
  =========
    bootTime: 2019-07-09 04:47:15.000000 UTC
    kernelVersion: 4.14.128-112.105.amzn2.x86_64
    os: linux
    platform: amazon
    platformFamily: rhel
    platformVersion: 2
    procs: 162
    uptime: 374h7m37s

  Hostnames
  =========
    ec2-hostname: redacted
    hostname: redacted
    instance-id: redacted
    socket-fqdn: redacted
    socket-hostname: redacted
    hostname provider: aws
    unused hostname providers:
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: status code 404 trying to GET http://169.254.169.254/computeMetadata/v1/instance/hostname

=========
Collector
=========



  Running Checks
  ==============

    cpu
    ---
      Instance ID: cpu [OK]
      Total Runs: 321
      Metric Samples: Last Run: 6, Total: 1,920
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    disk (2.4.0)
    ------------
      Instance ID: disk:e5dffb8bef24336f [OK]
      Total Runs: 321
      Metric Samples: Last Run: 54, Total: 17,334
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 29ms


    file_handle
    -----------
      Instance ID: file_handle [OK]
      Total Runs: 320
      Metric Samples: Last Run: 5, Total: 1,600
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    io
    --
      Instance ID: io [OK]
      Total Runs: 321
      Metric Samples: Last Run: 39, Total: 12,492
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    load
    ----
      Instance ID: load [OK]
      Total Runs: 320
      Metric Samples: Last Run: 6, Total: 1,920
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    memory
    ------
      Instance ID: memory [OK]
      Total Runs: 321
      Metric Samples: Last Run: 17, Total: 5,457
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    network (1.11.0)
    ----------------
      Instance ID: network:e0204ad63d43c949 [OK]
      Total Runs: 320
      Metric Samples: Last Run: 55, Total: 17,600
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 2ms


    ntp
    ---
      Instance ID: ntp:b4579e02d1981c12 [OK]
      Total Runs: 321
      Metric Samples: Last Run: 1, Total: 321
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 321
      Average Execution Time : 3ms


    uptime
    ------
      Instance ID: uptime [OK]
      Total Runs: 320
      Metric Samples: Last Run: 1, Total: 320
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s

========
JMXFetch
========

  Initialized checks
  ==================
    no checks

  Failed checks
  =============
    no checks

=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 320
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 26
    Metadata: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 666
    TimeseriesV1: 320

  API Keys status
  ===============
    API key ending with 3581e: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - 3581e

==========
Logs Agent
==========
    LogsProcessed: 18
    LogsSent: 18

  pritunl
  -------
    Type: file
    Path: /var/log/pritunl_journal.log
    Status: OK
    Inputs: /var/log/pritunl_journal.log
    Type: file
    Path: /var/log/pritunl_journal_test.log
    Status: OK
    Inputs: /var/log/pritunl_journal_test.log

=========
Aggregator
=========
  Checks Metric Sample: 64,103
  Dogstatsd Metric Sample: 20,199
  Event: 1
  Events Flushed: 1
  Number Of Flushes: 320
  Series Flushed: 60,369
  Service Check: 2,891
  Service Checks Flushed: 3,205

=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 20,198
  Metric Parse Errors: 0
  Service Check Packets: 0
  Service Check Parse Errors: 0
  Udp Bytes: 1.2 M
  Udp Packet Reading Errors: 0
  Udp Packets: 20,199
  Uds Bytes: 0
  Uds Origin Detection Errors: 0
  Uds Packet Reading Errors: 0
  Uds Packets: 0)
```

my config: 
```
logs:
  - type: file
    path: /var/log/pritunl_journal.log
    service: pritunl.audit
    source: pritunl
    log_processing_rules:
       - type: multi_line
         name: new_log_start_with_json_bracket
         pattern: \{

  - type: file
    path: /var/log/pritunl_journal_test.log
    service: pritunl.audit
    source: pritunl
    log_processing_rules:
       - type: multi_line
         name: new_log_start_with_json_bracket
         pattern: \{
```

**Describe what happened:**
JSON file based log submitted, agent correctly setup to read it, it does not like timestamp field, despite timestamp field conforming to unixtime.  (code uses python 2.7.*  time.time() ).

**Describe what you expected:**
The log should be read into the live tail on the backend and be processed correctly, it does not.

**Steps to reproduce the issue:**
Using a sample log file from here (you'll have to fix the json as there's an extra comma at the end)  https://docs.pritunl.com/docs/auditing .   

If the timestamp is double quoted (and reasonably current), it gets processed into the back end, but it does not accept the timestamp as being official on the back end per https://docs.datadoghq.com/logs/processing/#date-attribute.   There are no changes to my account that would change the default behavior otherwise, it's very stock.

If the timestamp is left by default (as a float, unquoted), the entry is outright ignored by the agent. (or backend? it doesn't show up in live tail)

If the timestamp field is removed, the log is processed, but since it's an audit log, it becomes inaccurate.

/opt/datadog/run/registry.json is parsing the file and keeping track of offset and lsof does show the file handles open.

**Additional environment details (Operating System, Cloud provider, etc):**
Amazon Linux 2.  Latest agent install as of today, previous agent did the same thing.  I do have a case open with support, multiple flares have been sent, etc.

**Comment by NBParis** [comment] 2019-07-30 08:30
Hello @bkruger99 ,

Thanks for submitting this and providing all those details. Would you mind sharing one log which timestamps is not properly processed?

This would be greatly helpful for us to in order to replicate the problem.

If you do not wish to share a log here, could you:

- Send an email to support@datadoghq.com with the log example
- If possible an URL to the log in question in Datadog

On a side note, you can find more information about how timestamp are handled in Datadog [here](https://docs.datadoghq.com/logs/faq/why-do-my-logs-not-have-the-expected-timestamp/#pagetitle).

Thanks a lot

**Comment by bkruger99** [comment] 2019-07-31 02:57
I've been working with support. Turns out it's the unix timestamp in milliseconds which is throwing things off.  (I haven't converted a timestamp from my logs yet, but that's what support has come back with.)

In python - time.time() for instance will return a float that might be accurate enough.   We run into problems with vendor code and them using that standard.  Unix timestamp support would make this a lot easier..

**Comment by bkruger99** [comment] 2019-07-31 03:38
Here's a sample log file for you though, in case we can get support for unix timestamps not in milliseconds.

`
{
  "id": "5c75cfc15285f54158d75a36",
  "timestamp": 1551224769.767757,
  "event": "admin_auth_failure",
  "reason": "invalid_username",
  "reason_long": "Invalid username",
  "host_id": "fbcf3dcc59874186a92065879e408627",
  "host_name": "pritunl0",
  "host_local_address": "8.8.8.8",
  "host_public_address": "8.8.8.8",
  "user_name": "testuser",
  "remote_address": "8.8.4.4",
}
`

**Comment by NBParis** [comment] 2019-08-02 12:32
Thanks for the sample.

So indeed today the only supported format for the date are epoch ms and ISO8601.

However do you have control over the structure of the log? Because if you were to send the timestamp as a string we could parse it to only take the first part.
We could have a grok parser with the following rule:

```
extracting_epoch %{number:timestamp_ms}.%{number}
```

And then use the `timestamp_ms` attribute to remap it to the date. The thing is that Grok Parsers only apply to strings which is why you would need to make sure that the timestamp is sent as a string.

Do you think that could work in your case?

**Comment by bkruger99** [comment] 2019-08-02 21:41
While I can make patches to the code, it becomes a maintenance burden of having to do so as the code is from the vendor. If the vendor deviates the code too much, that would cause breakage and now becomes a burden to manage patches to code every time there's a version change, assuming in future versions I get the option to modify code.

The ability to have unix timestamp parsed as a float would be great, even if it needs to be explicitly set as a timestamp format option in the config file.  This would cover you for more time edge cases too rather than having to grok/map/etc if someone is already using one of the reserved attributes.  (Modifying reserved attribute mapping pipeline can potentially break something else that isn't evident right away.)

**Comment by bkruger99** [comment] 2019-09-16 23:39
I am going to make an additional comment on this.  Support of POSIX (Unix) Timestamps is all over the Metrics API documentation.  Not milliseconds, seconds.  Please consider adding support for seconds as well.  Thanks.

**Comment by EricZaporzan** [comment] 2020-08-14 17:28
Just commenting here as I ran into the exact same issue, and was able to work around it by creating a pipeline using the Arithmetic Processor and the Date Remapper.

![image](https://user-images.githubusercontent.com/10189420/90276378-0a850c00-de21-11ea-80b2-df9db336bc09.png)

![image](https://user-images.githubusercontent.com/10189420/90276432-2092cc80-de21-11ea-97bd-affab5051020.png)

After making those changes logs started coming in with accurate timestamps. Hope this helps someone

**Comment by LanceSandino** [comment] 2021-09-07 23:11
@EricZaporzan was there a specific order in your pipelines these are in?
Your solution is not working for us. We are waiting for DD to provide feedback in our ticket.

Seems like logs aren't even shipping to datadog and the datadog agent is just tossing them.

**Comment by bkruger99** [comment] 2021-11-02 01:01
> @EricZaporzan was there a specific order in your pipelines these are in? Your solution is not working for us. We are waiting for DD to provide feedback in our ticket.
> 
> Seems like logs aren't even shipping to datadog and the datadog agent is just tossing them.

That was the issue I was running into.  The agent didn't even pick them up to ship them.

**Comment by LanceSandino** [comment] 2021-11-02 01:04
> > @EricZaporzan was there a specific order in your pipelines these are in? Your solution is not working for us. We are waiting for DD to provide feedback in our ticket.
> > Seems like logs aren't even shipping to datadog and the datadog agent is just tossing them.
> 
> That was the issue I was running into. The agent didn't even pick them up to ship them.

Yeah we ended up figuring it out. DD was getting them but tossing because of issue with time stamp. 

![173AEC25-487B-4531-B317-A15350F360EB](https://user-images.githubusercontent.com/1300195/139770332-4841704a-9a7f-4dfa-ab5d-7c108ea04a70.jpeg)

**Comment by gcaride** [comment] 2022-01-05 14:16
Hi!
We are running the same issue with pritunl, do you have any solution at the moment or provided by DataDog?

**Comment by olivielpeau** [comment] 2022-01-10 19:08
As far as I can tell the various problems listed in this issue were all related to converting timestamp to milliseconds, which can require a date remapper pipeline to be configured (with some conversions in some cases). Thanks all for sharing your solutions here.

I'll go ahead and close this issue since as far as I can tell there are no issues to resolve on the Agent. If you have further problems with processing timestamps in logs sent to Datadog, please reach out to [Datadog's support team](https://docs.datadoghq.com/help/), thanks!

**Closed by olivielpeau** 2022-01-10 19:08 UTC
Labels: [deprecated] team/logs

**Comment by raj-saxena** [comment] 2024-01-30 11:35
We are suffering from the same issue with a 3rd party service that generates **JSON** logs with the Unix time format i.e., the number of _seconds_ since Epoch (Example - `1706609988.788818`).
![image](https://github.com/DataDog/datadog-agent/assets/6253803/8b17efad-5421-4d27-9e01-60e06d2d82cc)

However, the issue is that [Datadog expects](https://docs.datadoghq.com/logs/log_configuration/pipelines/?tab=date#preprocessing) _milliseconds_ for this format.
<img width="864" alt="image" src="https://github.com/DataDog/datadog-agent/assets/6253803/5f3e2db6-3f19-4d8b-b6a6-21522f1989bf">

Datadog support suggested removing `timestamp` from the JSON preprocessing pipeline but that would affect all of the other log pipelines where this field should be used as the default date. We want to avoid touching at multiple places because that can create bugs. 

We are surprised that this format is not supported by Datadog by default. The 3rd party service uses [Zap library](https://github.com/uber-go/zap) which is quite popular in the Golang world.
Any suggestions/workarounds @olivielpeau?

@bkruger99 did you find a solution (since you seem to have your logs in JSON too)?
