### ISSUE TITLE
[BUG] CMD API Server Error

### ISSUE THREAD

**Issue by Nirzak** [DataDog/datadog-agent#24046] opened 2024-03-25 05:12 UTC
**Agent Environment**
[oracle@app01 datadog-agent]$ datadog-agent version
Agent 7.52.0 - Commit: 4a6318a - Serialization version: v5.0.104 - Go version: go1.21.8

**Describe what happened:**
The following error keep coming on agent.log file after updating the datadog agent to latest version.

2024-03-25 01:09:07 EDT | CORE | ERROR | (comp/api/api/apiimpl/utils/observability.go:32 in func2) | CMD API Server: POST /agent/jmx/status from 127.0.0.1:54912 to localhost:5001 took 141.251µs and returned http code 0

**Describe what you expected:**
Previously there's no such errors.

**Additional environment details (Operating System, Cloud provider, etc):**
Oracle Linux 7.9
Java Version: "1.8.0_401"

**Comment by st-cyrill** [comment] 2024-03-25 06:38
I'm encountering the same issue as well. As a workaround, I'm avoiding it by fixing the agent version to 7.51.1.

**Comment by Nirzak** [comment] 2024-03-25 09:09
> I'm encountering the same issue as well. As a workaround, I'm avoiding it by fixing the agent version to 7.51.1.

Yeah, we have done the same and the error was not coming on version 7.51.1 so looks like it might be related with version 7.52

**Comment by credpath-seek** [comment] 2024-03-26 00:20
Also experiencing this since a recent deployment, presumably due to pulling the latest agent / `-jmx` image with 7.52

**Comment by st-cyrill** [comment] 2024-03-27 05:25
https://github.com/DataDog/datadog-agent/pull/24093

**Comment by Nirzak** [comment] 2024-03-27 06:38
> Related PR: #24093

Thanks for the PR

**Comment by pgimalac** [comment] 2024-03-27 09:27
Hello, thank you for opening this issue, we are aware of it and it will be fixed by https://github.com/DataDog/datadog-agent/pull/24093 (in 7.53).

_TL;DR: this is not a new bug in 7.52, only improved logging, so you can ignore the error log for now and it will be fixed in the next release_

To give some context, we improved the logging of the agent's API server in 7.52 in order to have logs whenever it returns some error.
This server is used by JMX to post its status every 15 seconds, and it seems like the endpoint actually never replied in case of success, hence the fix being just "reply OK if there is no error".
This is not a bug in 7.52, the only thing that changed is the added logging which made this issue visible 😄
Sorry for the inconvenience !

**Comment by cptkng** [comment] 2024-04-30 16:00
Shall this one be closed, too, as https://github.com/DataDog/datadog-agent/pull/24093 is now merged?

**Comment by pgimalac** [comment] 2024-04-30 20:53
👋 Hey @cptkng, this issue should have been auto-closed when the PR was merged but I guess something didn't work.
Thanks for notifying !

**Closed by pgimalac** 2024-04-30 20:53 UTC
Labels: team/agent-shared-components
