### ISSUE TITLE
[BUG] Agent v7.40.0 fails to get hostname from Kubernetes causing a crash loop

### ISSUE THREAD

**Issue by JamieSinn** [DataDog/datadog-agent#14152] opened 2022-11-02 17:05 UTC
After Keel upgraded from 7.39.2 today at 12:11PM ET - we now have our pod failing to start because it cannot retrieve a hostname.
Logs from the agent pod attached.

**Agent Environment**

[datadog-agent-failing-to-get-hostname.txt](https://github.com/DataDog/datadog-agent/files/9922611/datadog-agent-failing-to-get-hostname.txt)

**Describe what happened:**
Upgrading to 7.40 via Keel - running image 
docker-pullable://public.ecr.aws/datadog/agent@sha256:05305e303d5056aa4c4919b77019926149dfc497031e062ba965c46734768cde                                                                                                               
**Describe what you expected:**
Hostname to be correctly identified.

**Steps to reproduce the issue:**
Run the above docker image under kubernetes. Specifically EKS for us.

**Additional environment details (Operating System, Cloud provider, etc):**

AWS EKS v1.21.14
Using public docker image

**Comment by christianbundy** [comment] 2022-11-02 19:09
Seeing similar behavior, our CI is reporting:

> Error: Error while getting hostname, exiting: unable to reliably determine the host name. You can define one in the agent config file or in your hosts file

And then crashing with:

> Error: unable to read authentication token file: open /etc/datadog-agent/auth_token: no such file or directory

**Comment by JamieSinn** [comment] 2022-11-02 21:00
Seems like the release notes touch on this; https://github.com/DataDog/datadog-agent/compare/7.39.2...7.40.0#diff-cf2b4696563d13f55549abf65ac5a23d2e280777f03753acdce2dd52d38498fc

**Comment by cmwilhelm** [comment] 2022-11-02 23:56
This also happens when running as a container in an EC2-ECS task. (Fargate-ECS seems fine).

**Comment by andreslon** [comment] 2022-11-03 05:46
same error here, running the deployment below:

`apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiSecret:
      secretName: datadog-secret
      keyName: api-key
    appSecret:
      secretName: datadog-secret
      keyName: app-key
  agent:
    config:
      collectEvents: true
    image:
      name: "gcr.io/datadoghq/agent:latest"
  clusterAgent:
    config:
      collectEvents: true
    image:
      name: "gcr.io/datadoghq/cluster-agent:latest"`


`2022-11-03 05:44:56 UTC | CORE | INFO | (pkg/util/log/log.go:588 in func1) | runtime: final GOMAXPROCS value is: 2
2022-11-03 05:44:56 UTC | CORE | WARN | (pkg/util/log/log.go:616 in func1) | Agent configuration relax permissions constraint on the secret backend cmd, Group can read and exec
2022-11-03 05:44:56 UTC | CORE | INFO | (pkg/util/log/log.go:588 in func1) | Features detected from environment: kubernetes,cri,containerd
2022-11-03 05:44:56 UTC | CORE | INFO | (cmd/agent/app/run.go:257 in StartAgent) | Starting Datadog Agent v7.40.0
2022-11-03 05:44:57 UTC | CORE | ERROR | (cmd/agent/app/run.go:313 in StartAgent) | Error while getting hostname, exiting: unable to reliably determine the host name. You can define one in the agent config file or in your hosts file
2022-11-03 05:44:57 UTC | CORE | INFO | (pkg/logs/logs.go:149 in Stop) | Stopping logs-agent
2022-11-03 05:44:57 UTC | CORE | INFO | (pkg/logs/logs.go:158 in Stop) | logs-agent stopped
2022-11-03 05:44:57 UTC | CORE | INFO | (cmd/agent/app/run.go:535 in StopAgent) | See ya!
Error: Error while getting hostname, exiting: unable to reliably determine the host name. You can define one in the agent config file or in your hosts file`

**Comment by vboulineau** [comment] 2022-11-03 09:35
Hello,

The change is indeed intended as explained in the `CHANGELOG`.
Having no proper hostname means that container name/pod name is used as hostname, which can lead to many features not working properly (poor visibility in Infrastructure list, inability to link with cloud integrations, etc.).

On Kubernetes, it usually means the Agent cannot access at least one of:
- Cloud provider metadata endpoint
- Kubelet API
- Docker runtime (if used)
Which means important features (tagging, autodiscovery, cloud integrations) won't work.

Check recommended Kubernetes setup for each major distribution at:
https://docs.datadoghq.com/containers/kubernetes/distributions

### Kubernetes

Solution 1: Make sure the Agent is able to access the Kubelet API. This is usually handled automatically by our Helm chart/Operator.
@JamieSinn It seems like you're not using Helm/Operator, check that the `Role/ClusterRole` assigned to the Agent has proper RBAC to access Kubelet API:
https://github.com/DataDog/helm-charts/blob/125a47e7f9ba9146499c0f5e87d42e06c1e19110/charts/datadog/templates/rbac.yaml#L70-L78

Solution 2: @andreslon On AKS (see distribution link above), you need to set (Operator):
```
datadog:
  kubelet:
    tlsVerify: false # Required as of Agent 7.35. See Notes.
```
Because Kubelet certificates on AKS are not properly signed (SAN missing).

Solution 3: Should only be necessary if you **explicitly** don't want the Agent to connect to Kubelet API (unlikely).
In this case you can use the downward API to set `DD_HOSTNAME`:

```
      env:
        - name: DD_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```

### ECS EC2

@cmwilhelm It means the Agent cannot access metadata API nor Docker socket.

You'd need to check why metadata API is not accessible (maybe you explicitly forbid access). 

But the easiest is to make sure the Docker socket is mounted as explained in our reference manifest: https://docs.datadoghq.com/resources/json/datadog-agent-ecs.json

### Docker VM/CI/etc.

The Docker socket should be mounted as explained in our [documentation](https://docs.datadoghq.com/containers/docker/?tab=standard):
```
-v /var/run/docker.sock:/var/run/docker.sock:ro
```

When running in a **CI environment** (e.g. Agent is not ephemeral), where the hostname is not really important, simply set `DD_HOSTNAME` to a value:
```
-e DD_HOSTNAME=$(hostname)
or
- e DD_HOSTNAME=<my_hardcoded_hostname>
```

**Comment by JamieSinn** [comment] 2022-11-03 16:23
Thanks for that info; we are using helm - but it seems like the version updates to the actual docker image are being overwritten by Keel. 

We were using an older version of the chart; which didn't have the env var set for the hostname.

I've marked the helm chart as ignore for keel; hopefully this fixes it in the future!


Thanks a lot!

**Comment by mkataja** [comment] 2022-11-03 19:02
We can only blame ourselves for deploying datadog-agent from the `latest` tag and having the datadog sidecar container marked as "essential" (ECS default). Still, releasing a breaking change as a minor version bump with just a small note at the end of the release notes is not exactly good practice IMO. :/

**Comment by cmwilhelm** [comment] 2022-11-03 19:14
Thanks for the detailed response @vboulineau. However, please consider saving these kinds of breaking changes for major version updates only in the future. Even if the agent was running in a slightly degraded fashion in <7.40.0, it doesn't make sense to deliberately break it altogether without warning -- such as a semver boundary at v8.

**Comment by cepefernando** [comment] 2022-11-03 22:42
Happened the same to us, we solved it by pinning the previous version in the installation script. One just needs to adde the following env variable on where you execute the installation of the DD Agent, this will then use the previous minor version, which in this case is `7.39.2`
```
DD_AGENT_MAJOR_VERSION=7 \
DD_AGENT_MINOR_VERSION=39
```

**Comment by lifeofguenter** [comment] 2022-11-04 07:41
It is unclear to me:

* why is this under "other notes" at the very bottom instead of being clearly signalized as **breaking change**
* why suddenly this is being reasoned as a core functionality of the agent, when it has been working all along just fine so far?
* why the hostname needs to be resolvable, something, that even outside of containers, is not always common practice

While this seems like an "open source" project, the fact and reality is that the majority of users here are paying customers, or even enterprise customers. I would like us to see more stable, backward compatible releases going forward. This should have been a toggable feature.

**Comment by scadu** [comment] 2022-11-04 08:27
I agree with @lifeofguenter. And even if it was better communicated, I would still expect a fallback, not crashing hard.

**Comment by dalgibbard** [comment] 2022-11-07 14:41
As per everyone else's sentiments; we run this in numerous places, from CICD to private orchestration platforms where this change broke our deployments on a "minor" release cadence.

Aside from the lost time in debugging this, only to eventually decide it must be a DD bug and come here; Now what we end up with is a massive user base of people pinning to v7.39 for eternity, which will surely only cause headaches for datadog in the long run, who will be left having to support users later down the line who never upgraded as the result of this change?

**Comment by epomatti** [comment] 2022-11-12 01:26
Same issue on Azure Container Apps.

Workaround using: `datadog/agent:7.39.2`

**Comment by lerlacher-haylix** [comment] 2022-11-18 01:01
Here is how to implement the DD_HOSTNAME workaround using helm:

```
  # datadog.env -- Set environment variables for all Agents
  ## The Datadog Agent supports many environment variables.
  ## ref: https://docs.datadoghq.com/agent/docker/?tab=standard#environment-variables
  env:
    - name: DD_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  #   - name: <ENV_VAR_NAME>
  #     value: <ENV_VAR_VALUE>
```

This results in the datadog agent correctly determining the hostname:

```
luke@ubu:~$ kubectl logs -n datadog-aue-dev            datadog-monitoring-linux-9sfpf -c security-agent
2022-11-18 00:57:52 UTC | SECURITY | WARN | (pkg/util/log/log.go:616 in func1) | Agent configuration relax permissions constraint on the secret backend cmd, Group can read and exec
2022-11-18 00:57:52 UTC | SECURITY | INFO | (pkg/util/log/log.go:588 in func1) | Features detected from environment: containerd,kubernetes,cri
2022-11-18 00:57:52 UTC | SECURITY | INFO | (app/app.go:265 in RunAgent) | Hostname is: aks-auedevscoa-30506518-vmss00006n
```

This is entirely undocumented and I had already decided to abandon upgrading to 7.40 before checking this out as one last thing.

It is extremely frustrating that the issue is not being acknowledged here and apparently no sufficient testing has taken place of this with AKS and helm as there is no useful guidance here and I have also not been able to get any useful guidance from a support ticket.

This is not what I expect from a supported paid for product.

**Comment by ricardoekm** [comment] 2022-11-23 23:08
Same issue here using helm + EKS :/ The TLS configuration didn't solve the problem for me.

I had to manually rollback the cluster agent version:
```
kubectl set image deployments/prod-datadog-cluster-agent cluster-agent=gcr.io/datadoghq/cluster-agent:7.39.2
```

**Comment by kmorkans-lumoa** [comment] 2022-12-12 07:28
```  kubelet:
    host:
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    hostCAPath: /etc/kubernetes/certs/kubeletserver.crt
    tlsVerify: false
```
this Helm config works on AKS, but it doesn't work with security-agent.
After 7.40 security-agent will fail with `Error: Error while getting hostname, exiting: unable to reliably determine the host name. You can define one in the agent config file or in your hosts file`

**Comment by damienleger** [comment] 2022-12-12 14:28
EKS (AWS) user here. I've been fighting for weeks with Datadog support on an EKS 1.24 migration. Seems like cluster name / nodename autodetection stuff or whatever doesn't work very well atm in EKS 1.24 (K8S 1.24 has removed dockershim, which Datadog agent relies on). So I end up here because, you know, support ask you to run the last version everytime. My advices for my fellow K8S admin here, don't try to upgrade to this Datadog version + to K8S 1.24 at once, the problem just add up it's a PITA to handle really.

Anyway. On my "old" EKS 1.23 I've tried to upgrade to agent 7.40+ (from chart 3.1.11 to 3.5.2) as well and it doesn't work.

I think I've found why however. So a bit of context, my EKS cluster is called `staging_v2`

a) Datadog is constructing the ${node-name}-${cluster-name} hostAlias, as explained here https://docs.datadoghq.com/agent/guide/kubernetes-cluster-name-detection/

b) there are functions to replace "_" by "-" in the cluster name in the code
https://github.com/DataDog/datadog-agent/blob/7.40.1/pkg/util/kubernetes/clustername/clustername.go#L77
https://github.com/DataDog/datadog-agent/blob/7.40.1/pkg/util/kubelet/hostname.go#L48

c) but this naming pattern isn't consistent, it's only applied in datadog-agent it seems

c1) the datadog-cluster-agent doesn't apply this "_" to "-" replacement. Resulting in inconsistency between hosts appearing in Infrastructure list panel in chart 3.1.11 that must probably count as different hosts on the bill I won't be surprised. ⚠️ and ALSO the root cause of the issue of what datadog-cluster-agent is not starting in 3.5.2

![image](https://user-images.githubusercontent.com/16499022/207068268-ee960860-9c21-477f-91e1-1f2ab0ae1dc8.png)
![image](https://user-images.githubusercontent.com/16499022/207068359-0ee68f88-3fcf-43e3-bacd-686e36a07eaa.png)
![image](https://user-images.githubusercontent.com/16499022/207068490-6a3739ca-9b0c-48ce-b5a8-ecc896aced82.png)

c2) the datadog-cluster-check override this logic at all by setting up the variable DD_HOSTNAME. See the link below
https://github.com/DataDog/helm-charts/blob/datadog-3.5.2/charts/datadog/templates/agent-clusterchecks-deployment.yaml#L180
resulting in the error in the logs sending you there https://github.com/DataDog/datadog-agent/blob/main/docs/agent/hostname_force_config_as_canonical.md (and btw because of the host naming pattern of EC2, the @lerlacher-haylix workaround doesn't work on EKS)

![image](https://user-images.githubusercontent.com/16499022/207068806-d3d13fb1-601a-4b9c-894b-4c23a01e5c9c.png)

I hope my post will get software engineers attention. I'm fed up of the support "gatekeeping" on this really 🙏

**Comment by aliciascott** [comment] 2022-12-15 21:01
Hi @damienleger can you go ahead and open a Support Ticket for this so we can look at it further? Thanks.

**Comment by damienleger** [comment] 2022-12-16 10:41
> Hi @damienleger can you go ahead and open a Support Ticket for this so we can look at it further? Thanks.

hello @aliciascott, I had one (https://help.datadoghq.com/hc/en-us/requests/1004544) but closed in after opt in for override manually clusterName for `staging-v2` (and `production-v2` for my other cluster) in values.yaml. This results in various mixes of "-" and "_" in tags unlike before (see below) but at least the helm chart now working correctly. It seems impossible to have support tickets escalated to expert team; I gave up tbh and opted for workaround instead.

![image](https://user-images.githubusercontent.com/16499022/208080103-9184f590-e0d5-471d-8227-3df6587ef769.png)
![image](https://user-images.githubusercontent.com/16499022/208080155-d90567d1-b3c9-4764-80fa-226c5a01ea57.png)

**Comment by clamoriniere** [comment] 2023-01-12 22:05
Hi @damienleger,

About the discrepancy issue that you describe for `hostname`  and `kube_cluster_name` between `agent` and `cluster-agent` in the comment https://github.com/DataDog/datadog-agent/issues/14152#issuecomment-1354538056. 
In your case the hostname is properly retrieved but the same "normalization" logic is not applied everywhere. 

So, I think it is not related to the initial bug tracked by this issue. However I do agree that what you are describing looks like a bug. I looked at the support ticket that you have mentioned (https://help.datadoghq.com/hc/en-us/requests/1004544), and I think I have some idea about where it comes from. If you like you can open a dedicated github issue with https://github.com/DataDog/datadog-agent/issues/14152#issuecomment-1354538056 in description, so that we can track separately your issue from this one. And please ping me in the new issue. (In any case I will add also a comment to the support ticket)

**Comment by damienleger** [comment] 2023-01-13 14:34
@clamoriniere hello, actually I've managed to do my EKS 1.24 migration. I've created an EKS without "_" in the name, but with "-" instead. And for some reason since automatic cluster name detection didn't work anymore I had to hardcode clustername in the helm values.yml. But anyway, now cluster is migrated and I don't have discrepancy issue anymore since there are no more "_"! More a workaround than a fix, but now I'm good with this issue. Up to you to create issue and fix if you want. I spent too many time on this, now I'm moving on :)

**Comment by vboulineau** [comment] 2023-01-30 11:39
Hello,

We've published a page dedicated to the configuration issues that could lead to have this error with Agent `>=7.40.0`.
It lists all the common cases and options available to fix the Agent setup/configuration.

It's available at: https://docs.datadoghq.com/agent/troubleshooting/hostname_containers

It also documents a new option, available since Agent `>=7.42.0`, because there are few cases where hostname cannot be retrieved AND `hostname` returns a correct value (for instance, LXC containers).

In these scenarios, you'll need to explicitly set the following option:
```
DD_HOSTNAME_TRUST_UTS_NAMESPACE (or hostname_trust_uts_namespace in datadog.yaml)
```

(Technically speaking, it will instruct the Agent to trust hostname retrieved from non-root UTS namespace, which will mimic the behaviour pre-7.40).

**Closed by vboulineau** 2023-01-30 11:39 UTC
Labels: team/triage

**Comment by greg-caffeine** [comment] 2023-02-03 21:22
@vboulineau, can you please specify how to set DD_HOSTNAME_TRUST_UTS_NAMESPACE if deploying Datadog in Kubernetes via the datadog-operator?

**Comment by Korsani** [comment] 2023-02-10 15:21
You can set env var DD_HOSTNAME_FILE to "/etc/hostname"

**Comment by MexsonFernandes** [comment] 2023-03-16 01:20
I got it resolved by adding the DD_HOSTNAME in the env part of datadog section.

```
...
datadog:
  ...
  env:
    - name: DD_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  ...
```

I am doing Helm setup on AKS cluster.

This might help someone so keeping reference for it.

Ref: https://docs.datadoghq.com/agent/troubleshooting/hostname_containers/?tab=helm#pagetitle
