### ISSUE TITLE
[BUG]  Datadog serverless plugin: LogMessage.UnmarshalJSON: can't read the spans object

### ISSUE THREAD

**Issue by inyutin** [DataDog/datadog-agent#14374] opened 2022-11-17 18:12 UTC
**Agent Environment**
Lambda extension v33
serverless-plugin-datadog v5.11.0

**Describe what happened:**
I use serverless-plugin-datadog v5.11.0. 
I've set it up by following [official guide for serverless framework](https://docs.datadoghq.com/serverless/installation/python/?tab=serverlessframework).

However, I constantly face unpleasant bug. If Lambda starts from cold position - then I see in logs the next error: 
```2022-11-17 17:39:46 UTC | DD_EXTENSION | ERROR | LogMessage.UnmarshalJSON: can't read the spans object```

Additionally, there are not real application logs after this line. However, they should be.
If lambda start from hot position - this error not occurs and all logs are present. 
I'm not sure, however, it seems there are no logs, because with this behaviout lambda became dead completely. 

I read source code a little bit and found out that this error was presented only 2 days ago by [this commit](https://github.com/DataDog/datadog-agent/commit/c9424d9cffd0aade5a4148a490586ff59345864e).
It seems, when processing message about lambda exit the plugin search for "spans" field. If there is no such field - it throws an error, which kills whole lambda. For some reason, this field presents in hot start, but not in cold ones, at least in default setup.

**Describe what you expected:**
serverless-framework-plugin shouldn't think that all trace metadata is mandatory. If there is no "spans" - don't throw error about this, just continue.

**Steps to reproduce the issue:**
1. serverless plugin install -n serverless-plugin-datadog@v5.11.0
2. Serverless.yaml:
```yaml
custom:
  datadog:
    site: datadoghq.eu
    apiKeySecretArn: arn:aws:secretsmanager:eu-west-2:077068547884:secret:DATADOG_API_KEY-ai9u6k
    tags: "stage:internal-test"
```

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by purple4reina** [comment] 2022-11-18 15:47
Hello @inyutin, thank you so much for reporting this issue. After investigating your report, I do not believe this is a bug. However, I do think that the log message is misleading. It should not be considered an error because normal execution of the extension continues after this point. This log message just indicates that we are unable to gather data for the `aws.lambda.enhanced.response_duration` and `aws.lambda.enhanced.response_latency` metrics. We will go ahead and update this message so it is less confusing.

I want to address your concern about there being no logs after this point. This log message is sent when the extension receives the `platform.runtimeDone` event from the lambda runtime. Therefore, your lambda function has already completed execution and returned its response. We would not expect any further customer generated function logs after this point.

I am concerned that you are having issues using the extension and are not seeing the data you would expect to see. We would like to help you with this. I encourage you to open a support ticket so we can work with you more closely to address your specific needs and concerns. For your request, please contact our [support](http://docs.datadoghq.com/help/) and send them all of the logs you are seeing for your running functions.

**Comment by purple4reina** [comment] 2022-11-18 17:14
I want to share a little more context now I've had a closer look at this issue. I suspect that other people could be seeing the `LogMessage.UnmarshalJSON: can't read the spans object` error as well. It is happening because the lambda runtime is not currently sending us spans as part of the `platform.runtimeDone` event.

The extension will continue to function properly without these spans. The only consequence is you will not see `aws.lambda.enhanced.response_latency` and `aws.lambda.enhanced.response_duration` metrics.

Again thank you @inyutin for filing this issue. We will keep an eye on the data lambda sends the extension for possible future changes. In the meantime I am going to close this issue.

**Closed by purple4reina** 2022-11-18 17:14 UTC
Labels: team/serverless

**Comment by bdevore17** [comment] 2022-12-08 18:30
We are seeing this in our lambdas too. What is the fix exactly?

**Comment by M3gar00** [comment] 2022-12-09 13:15
I just got this with DD Extension Layer 35. It's showing up in our local Error log reporting, but is not being passed to Datadog. We are using DD Library Layer 39:60. 

Is there a fix for this behavior?

**Comment by inyutin** [comment] 2022-12-10 10:52
@purple4reina I would not argue with you, but I want to clarify the behaviour I had.
When I tried to use it, I got those errors in AWS cloudwatch and nothing had passed into Datadog.

@bdevore17 @M3gar00 the fix is use previous version of datadog plugin:
```
"serverless-plugin-datadog": "^5.11.0",
```

Once I downgraded it started to work fine.

**Comment by bkk-bcd** [comment] 2022-12-13 22:45
What if we set `DD_APM_ENABLED=false` (assuming we don't care about tracing)?

**Comment by coilysiren** [comment] 2022-12-17 04:46
I've found that this happens if your lambda crashes very early in its init process. It should reproduce via something like this:

```python
def handler(event, context):
    1/0
```

**Comment by purple4reina** [comment] 2022-12-23 16:52
Hi all, thanks again for your reports. I've spoken with AWS and spent some time looking at this in depth and have a way forward for each of you.

To start out, I believe that there may be more than one thing going on here, and that those things may differ for each of you. @coilysiren is correct when they pointed out that if your function errors, either during init or normal runtime, you will see the `LogMessage.UnmarshalJSON: can't read the spans object` error in your logs. We've determined that this is to be expected. Makes sense that we won't be able to tell you your response latency/duration if there was no response.

I recognize that some of you are also reporting that you are not seeing any data in Datadog for your functions and that this seems to correlate with seeing this log message. Nothing about missing the spans object will prevent your functions from reporting, therefore, there is something else going on. If this is applies to you, please first check to make sure your lambda isn't finishing with an error. Afterwards, if you still believe there is an issue, please open a support ticket at https://help.datadoghq.com so we can work with you more closely to address your specific needs.

Again, thanks for all your comments. I hope this helps everyone move forward. I'm happy to respond to if anything here needs clarifying.

**Comment by bkk-bcd** [comment] 2022-12-23 19:22
Thanks @purple4reina! In general I'd rather see errors generated from the root cause and/or include a stacktrace. My function having an issue and then the error making it look like its from the datadog layer isn't ideal. It's causing confusion for end users and I'd think create unnecessary churn on your support side. Or maybe there's some error handling guidance implementors need that we are missing so we catch it sooner?

**Comment by jmaixl** [comment] 2023-01-24 19:50
As a followup to this, I started having this error when i added `DD_TRACE_DISABLED_PLUGINS` to my code to exclude some unnecessary traces.

**Comment by purple4reina** [comment] 2023-01-31 17:16
> Thanks @purple4reina! In general I'd rather see errors generated from the root cause and/or include a stacktrace. My function having an issue and then the error making it look like its from the datadog layer isn't ideal. It's causing confusion for end users and I'd think create unnecessary churn on your support side. Or maybe there's some error handling guidance implementors need that we are missing so we catch it sooner?

I wholeheartedly agree @bkk-bcd! Which is why if you upgrade to using the Datadog Lambda Extension v36 you will see we've changed this log statement to a debug level to cut down on confusion.

So, if you are seeing `LogMessage.UnmarshalJSON: can't read the spans object` in your logs, the solution is to upgrade to the latest v36 of the extension.

**Comment by bkk-bcd** [comment] 2023-01-31 17:24
> > Thanks @purple4reina! In general I'd rather see errors generated from the root cause and/or include a stacktrace. My function having an issue and then the error making it look like its from the datadog layer isn't ideal. It's causing confusion for end users and I'd think create unnecessary churn on your support side. Or maybe there's some error handling guidance implementors need that we are missing so we catch it sooner?
> 
> I wholeheartedly agree @bkk-bcd! Which is why if you upgrade to using the Datadog Lambda Extension v36 you will see we've changed this log statement to a debug level to cut down on confusion.
> 
> So, if you are seeing `LogMessage.UnmarshalJSON: can't read the spans object` in your logs, the solution is to upgrade to the latest v36 of the extension.

Nice thanks!
