### ISSUE TITLE
Dogstatsd: dns lookup failed with "no such host" in container environment

### ISSUE THREAD

**Issue by sfozz** [DataDog/datadog-agent#11338] opened 2022-03-18 00:32 UTC
**Describe what happened:**
We recently updated the dogstatsd container in one of our environments. Following this we started seeing errors like:
```
2022-03-18 00:20:58 UTC | DSD | ERROR | (pkg/forwarder/worker.go:183 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post "https://7-32-0-app.agent.datadoghq.com/intake/?api_key=***************************2f6f0": dial tcp: lookup 7-32-0-app.agent.datadoghq.com: no such host
```

However shelling into the container and running `getent hosts 7-32-0-app.agent.datadoghq.com` worked. This confirmed that DNS was working and we could see the query heading out over the `veth` interface in a tcpdump.

We then investigated further and captured traffic from the container before dogstatsd started up and found that there was no query for the hostname.

A bit of googling discovered https://github.com/golang/go/issues/18588.

Adding `GODEBUG=netdns=go` to the environment of the container addressed the issue.

We also confirmed that the container was not running out of file descriptors (limit was set to 1048576).

Using `cgo` DNS Resolver
```
ubuntu@ip-10-0-1-8:~$ docker run -ti -e DD_API_KEY=XYXYXYXYXYXYXYXYX -e DD_TAGS=ATAG -e GODEBUG=netdns=cgo+2 --rm --network project_default --name  dogstatsd datadog/dogstatsd:latest
2022-03-18 00:28:26 UTC | DSD | INFO | (pkg/util/log/log.go:610 in func1) | Features detected from environment: 
2022-03-18 00:28:26 UTC | DSD | INFO | (pkg/forwarder/forwarder.go:205 in NewDefaultForwarder) | Retry queue storage on disk is disabled
2022-03-18 00:28:26 UTC | DSD | INFO | (pkg/forwarder/forwarder.go:304 in Start) | Forwarder started, sending to 1 endpoint(s) with 1 worker(s) each: "https://7-32-0-app.agent.datadoghq.com" (1 api key(s))
go package net: using cgo DNS resolver
go package net: hostLookupOrder(api.datadoghq.com) = cgo
go package net: hostLookupOrder(localhost) = cgo
go package net: hostLookupOrder(a83a871de77d) = cgo
2022-03-18 00:28:27 UTC | DSD | INFO | (pkg/metadata/host/host.go:216 in getNetworkMeta) | Adding public IPv4 13.239.164.66 to network metadata
go package net: hostLookupOrder(7-32-0-app.agent.datadoghq.com) = cgo
2022-03-18 00:28:27 UTC | DSD | INFO | (pkg/serializer/serializer.go:371 in sendMetadata) | Sent metadata payload, size (raw/compressed): 1079/623 bytes.
2022-03-18 00:28:27 UTC | DSD | ERROR | (pkg/forwarder/worker.go:183 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post "https://7-32-0-app.agent.datadoghq.com/intake/?api_key=***************************2f6f0": dial tcp: lookup 7-32-0-app.agent.datadoghq.com: no such host
2022-03-18 00:28:27 UTC | DSD | INFO | (pkg/dogstatsd/listeners/udp.go:95 in Listen) | dogstatsd-udp: starting to listen on [::]:8125
go package net: hostLookupOrder(7-32-0-app.agent.datadoghq.com) = cgo
2022-03-18 00:28:31 UTC | DSD | ERROR | (pkg/forwarder/worker.go:183 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post "https://7-32-0-app.agent.datadoghq.com/intake/?api_key=***************************2f6f0": dial tcp: lookup 7-32-0-app.agent.datadoghq.com: no such host
```
Using  `go` DNS Resolver
```
ubuntu@ip-10-0-1-8:~$ docker run -ti -e DD_API_KEY=XYXYXYXYXYXYXYXYX -e DD_TAGS=ATAG -e GODEBUG=netdns=go+2 --rm --network project_default --name  dogstatsd datadog/dogstatsd:latest
2022-03-18 00:30:06 UTC | DSD | INFO | (pkg/util/log/log.go:610 in func1) | Features detected from environment: 
2022-03-18 00:30:06 UTC | DSD | INFO | (pkg/forwarder/forwarder.go:205 in NewDefaultForwarder) | Retry queue storage on disk is disabled
2022-03-18 00:30:06 UTC | DSD | INFO | (pkg/forwarder/forwarder.go:304 in Start) | Forwarder started, sending to 1 endpoint(s) with 1 worker(s) each: "https://7-32-0-app.agent.datadoghq.com" (1 api key(s))
go package net: GODEBUG setting forcing use of Go's resolver
go package net: hostLookupOrder(api.datadoghq.com) = files,dns
go package net: hostLookupOrder(localhost) = files,dns
go package net: hostLookupOrder(83c9338f8807) = files,dns
go package net: hostLookupOrder() = files,dns
2022-03-18 00:30:08 UTC | DSD | INFO | (pkg/metadata/host/host.go:216 in getNetworkMeta) | Adding public IPv4 13.239.164.66 to network metadata
go package net: hostLookupOrder(7-32-0-app.agent.datadoghq.com) = files,dns
2022-03-18 00:30:08 UTC | DSD | INFO | (pkg/serializer/serializer.go:371 in sendMetadata) | Sent metadata payload, size (raw/compressed): 1079/625 bytes.
2022-03-18 00:30:08 UTC | DSD | INFO | (pkg/dogstatsd/listeners/udp.go:95 in Listen) | dogstatsd-udp: starting to listen on [::]:8125
2022-03-18 00:30:09 UTC | DSD | INFO | (pkg/forwarder/transaction/transaction.go:365 in internalProcess) | Successfully posted payload to "https://7-32-0-app.agent.datadoghq.com/intake/?api_key=***************************2f6f0", the agent will only log transaction success every 500 transactions
```

**Describe what you expected:**

The error "no such host" would not be reported.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**
- AWS
- Ubuntu 18 LTS
- docker 20.10
- datadog/dogstatsd:7 (058ed2709f8d)

**Comment by djmitche** [comment] 2022-03-21 19:18
It seems that the linked bug, about fd exhaustion, was fixed in a long-ago go version, to give a more appropriate error message.  So, that's likely not the precise culprit.  However, that `GODEBUG=netdns=go` is a workaround indicates this is some kind of bug in the Go resolver.

When you initially observed this error, were you using `GODEBUG=netdns=go` or leaving that at its default?  Note that you can set `GODEBUG=netdns=2` to get the debug info without forcing the choice, which should help to determine the default.

If left at its default, perhaps you can determine a regression window of affected dogstatsd images?

**Comment by sfozz** [comment] 2022-03-25 00:28
When we discovered the error we did not have `GODEBUG=netdns=go` or `GODEBUG=netdns=cgo` set.

Just run some tests and get the following results:

```shell
$ docker run -ti -e DD_API_KEY=xyxyxyxyxyxy -e DD_TAGS=web -e GODEBUG=netdns=2 --network web_default datadog/dogstatsd:latest
2022-03-25 00:15:55 UTC | DSD | INFO | (pkg/util/log/log.go:572 in func1) | Features detected from environment: 
go package net: dynamic selection of DNS resolver
go package net: hostLookupOrder(localhost) = cgo
2022-03-25 00:15:56 UTC | DSD | INFO | (pkg/forwarder/forwarder.go:225 in NewDefaultForwarder) | Retry queue storage on disk is disabled
go package net: hostLookupOrder(api.datadoghq.com) = cgo
2022-03-25 00:15:56 UTC | DSD | INFO | (pkg/forwarder/forwarder.go:328 in Start) | Forwarder started, sending to 1 endpoint(s) with 1 worker(s) each: "https://7-34-0-app.agent.datadoghq.com" (1 api key(s))
go package net: hostLookupOrder(a433cc5b2815) = cgo
2022-03-25 00:15:57 UTC | DSD | INFO | (pkg/metadata/host/host.go:170 in getNetworkMeta) | Adding public IPv4 52.64.170.227 to network metadata
go package net: hostLookupOrder(7-34-0-app.agent.datadoghq.com) = cgo
2022-03-25 00:15:57 UTC | DSD | INFO | (pkg/serializer/serializer.go:427 in sendMetadata) | Sent metadata payload, size (raw/compressed): 1101/629 bytes.
2022-03-25 00:15:57 UTC | DSD | WARN | (pkg/config/viper.go:196 in GetStringSlice) | failed to get configuration value for key "proxy.no_proxy": unable to cast <nil> of type <nil> to []string
2022-03-25 00:15:57 UTC | DSD | ERROR | (pkg/forwarder/worker.go:183 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post "https://7-34-0-app.agent.datadoghq.com/intake/?api_key=***************************2f6f0": dial tcp: lookup 7-34-0-app.agent.datadoghq.com: no such host
2022-03-25 00:15:57 UTC | DSD | INFO | (pkg/dogstatsd/listeners/udp.go:95 in Listen) | dogstatsd-udp: starting to listen on [::]:8125
go package net: hostLookupOrder(7-34-0-app.agent.datadoghq.com) = cgo
2022-03-25 00:16:01 UTC | DSD | ERROR | (pkg/forwarder/worker.go:183 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post "https://7-34-0-app.agent.datadoghq.com/intake/?api_key=***************************2f6f0": dial tcp: lookup 7-34-0-app.agent.datadoghq.com: no such host
^C2022-03-25 00:16:03 UTC | DSD | INFO | (cmd/dogstatsd/main.go:248 in handleSignals) | Received signal 'interrupt', shutting down...
2022-03-25 00:16:03 UTC | DSD | WARN | (cmd/dogstatsd/main.go:262 in stopAgent) | Some components were unhealthy: [dogstatsd-main aggregator metadata-host metadata-inventories forwarder]
2022-03-25 00:16:03 UTC | DSD | INFO | (cmd/dogstatsd/main.go:277 in stopAgent) | See ya!
```
``` shell
$ docker run -ti -e DD_API_KEY=xyxyxyxyxy -e DD_TAGS=web -e GODEBUG=netdns=2 --network bridge datadog/dogstatsd:latest
2022-03-25 00:18:44 UTC | DSD | INFO | (pkg/util/log/log.go:572 in func1) | Features detected from environment: 
go package net: dynamic selection of DNS resolver
go package net: hostLookupOrder(localhost) = files,dns
2022-03-25 00:18:45 UTC | DSD | INFO | (pkg/forwarder/forwarder.go:225 in NewDefaultForwarder) | Retry queue storage on disk is disabled
go package net: hostLookupOrder(api.datadoghq.com) = files,dns
2022-03-25 00:18:45 UTC | DSD | INFO | (pkg/forwarder/forwarder.go:328 in Start) | Forwarder started, sending to 1 endpoint(s) with 1 worker(s) each: "https://7-34-0-app.agent.datadoghq.com" (1 api key(s))
go package net: hostLookupOrder(4d453af27121) = files,dns
go package net: hostLookupOrder() = files,dns
2022-03-25 00:18:45 UTC | DSD | INFO | (pkg/metadata/host/host.go:170 in getNetworkMeta) | Adding public IPv4 52.64.170.227 to network metadata
go package net: hostLookupOrder(7-34-0-app.agent.datadoghq.com) = files,dns
2022-03-25 00:18:45 UTC | DSD | INFO | (pkg/serializer/serializer.go:427 in sendMetadata) | Sent metadata payload, size (raw/compressed): 1101/631 bytes.
2022-03-25 00:18:45 UTC | DSD | WARN | (pkg/config/viper.go:196 in GetStringSlice) | failed to get configuration value for key "proxy.no_proxy": unable to cast <nil> of type <nil> to []string
2022-03-25 00:18:45 UTC | DSD | INFO | (pkg/dogstatsd/listeners/udp.go:95 in Listen) | dogstatsd-udp: starting to listen on [::]:8125
2022-03-25 00:18:46 UTC | DSD | INFO | (pkg/forwarder/transaction/transaction.go:366 in internalProcess) | Successfully posted payload to "https://7-34-0-app.agent.datadoghq.com/intake/?api_key=***************************2f6f0", the agent will only log transaction success every 500 transactions
^C2022-03-25 00:18:52 UTC | DSD | INFO | (cmd/dogstatsd/main.go:248 in handleSignals) | Received signal 'interrupt', shutting down...
2022-03-25 00:18:52 UTC | DSD | WARN | (cmd/dogstatsd/main.go:262 in stopAgent) | Some components were unhealthy: [aggregator metadata-host metadata-inventories dogstatsd-main forwarder]
2022-03-25 00:18:52 UTC | DSD | INFO | (cmd/dogstatsd/main.go:277 in stopAgent) | See ya!
```

So using the network created by docker compose results in different behaviour than the default bridge network. IIRC there is a difference between them, but `docker network inspect` isn't showing it.

**Comment by djmitche** [comment] 2022-03-25 16:09
It looks like [this](https://github.com/golang/go/blob/master/src/net/conf.go#L70-L113) is the logic to determine which resolver to use, and it's based on some env vars and accessibility of /etc/resolv.conf.  Presumably the different docker-compose networks affect one of those values.

Does forcing the cgo resolver in the `bridge` network still fail?  If not, then the issue may be with the DNS support in the `web_default` network -- perhaps that's using dnsmasq or something like it, and that is causing the errors?

**Comment by djmitche** [comment] 2022-04-06 19:46
Let's re-open this if there's further information to help debug :)

**Closed by djmitche** 2022-04-06 19:46 UTC

**Comment by sfozz** [comment] 2022-04-08 02:10
Yes it does fail when using the `bridge` network and forcing the use of the `cgo` resolver

```
$ docker run --rm -ti -e DD_API_KEY=XYXYXYXYXYXYXY -e DD_TAGS=web -e GODEBUG=netdns=cgo+2 --network bridge datadog/dogstatsd:latest
2022-04-08 02:06:13 UTC | DSD | INFO | (pkg/util/log/log.go:572 in func1) | Features detected from environment: 
go package net: using cgo DNS resolver
go package net: hostLookupOrder(localhost) = cgo
2022-04-08 02:06:14 UTC | DSD | INFO | (pkg/forwarder/forwarder.go:225 in NewDefaultForwarder) | Retry queue storage on disk is disabled
go package net: hostLookupOrder(api.datadoghq.com) = cgo
2022-04-08 02:06:14 UTC | DSD | INFO | (pkg/forwarder/forwarder.go:328 in Start) | Forwarder started, sending to 1 endpoint(s) with 1 worker(s) each: "https://7-34-0-app.agent.datadoghq.com" (1 api key(s))
go package net: hostLookupOrder(5692c384b138) = cgo
2022-04-08 02:06:14 UTC | DSD | INFO | (pkg/metadata/host/host.go:170 in getNetworkMeta) | Adding public IPv4 52.62.153.137 to network metadata
go package net: hostLookupOrder(7-34-0-app.agent.datadoghq.com) = cgo
2022-04-08 02:06:14 UTC | DSD | INFO | (pkg/serializer/serializer.go:427 in sendMetadata) | Sent metadata payload, size (raw/compressed): 1105/632 bytes.
2022-04-08 02:06:14 UTC | DSD | WARN | (pkg/config/viper.go:196 in GetStringSlice) | failed to get configuration value for key "proxy.no_proxy": unable to cast <nil> of type <nil> to []string
2022-04-08 02:06:14 UTC | DSD | INFO | (pkg/dogstatsd/listeners/udp.go:95 in Listen) | dogstatsd-udp: starting to listen on [::]:8125
2022-04-08 02:06:14 UTC | DSD | ERROR | (pkg/forwarder/worker.go:183 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post "https://7-34-0-app.agent.datadoghq.com/intake/?api_key=***************************2f6f0": dial tcp: lookup 7-34-0-app.agent.datadoghq.com: no such host
go package net: hostLookupOrder(7-34-0-app.agent.datadoghq.com) = cgo
2022-04-08 02:06:19 UTC | DSD | ERROR | (pkg/forwarder/worker.go:183 in process) | Error while processing transaction: error while sending transaction, rescheduling it: Post "https://7-34-0-app.agent.datadoghq.com/intake/?api_key=***************************2f6f0": dial tcp: lookup 7-34-0-app.agent.datadoghq.com: no such host
^C2022-04-08 02:06:20 UTC | DSD | INFO | (cmd/dogstatsd/main.go:248 in handleSignals) | Received signal 'interrupt', shutting down...
2022-04-08 02:06:20 UTC | DSD | WARN | (cmd/dogstatsd/main.go:262 in stopAgent) | Some components were unhealthy: [aggregator metadata-host metadata-inventories dogstatsd-main forwarder]
2022-04-08 02:06:20 UTC | DSD | INFO | (cmd/dogstatsd/main.go:277 in stopAgent) | See ya!
```
