### ISSUE TITLE
[BUG] Failing query in `datadogmetric` causes multiple HPA to fail

### ISSUE THREAD

**Issue by alam0rt** [DataDog/datadog-agent#20183] opened 2023-10-17 06:14 UTC
**Agent Environment**

```
Datadog Cluster Agent (v7.44.0)
```

**Describe what happened:**

A change to a metric (removal of aggregation configuration) caused many HPAs to fail querying for scaling metrics.

The below error was seen on the `datadogmetric` status (which funnily _shouldn't ever happen_ https://github.com/DataDog/datadog-agent/blob/main/pkg/clusteragent/externalmetrics/metrics_retriever.go#L189-L192)
```
  - lastTransitionTime: "2023-10-16T18:44:35Z"
    lastUpdateTime: "2023-10-17T05:49:24Z"
    message: 'Unexpected error, query data not found in result, query: 
```

Since the bad query was one of  `DD_EXTERNAL_METRICS_PROVIDER_CHUNK_SIZE`, _all_ queries in the chunk failed causing HPAs to be unable to scale.

**Describe what you expected:**
We expect a single metric failing to not affect unrelated HPA scaling metrics.

**Steps to reproduce the issue:**
- Create a metric which returns an error like this

```json
{
  "status": "error",
  "res_type": "time_series",
  "resp_version": 1,
  "query": "avg:foo_metric",
  "from_date": 1697483891000,
  "to_date": 1697487551000,
  "series": [],
  "values": [],
  "times": [],
  "error": "Invalid query input:\n",
  "group_by": []
}
```
- Use this metric as part of a `datadogmetric` resource associated with an HPA
- Ensure chunk size is `> 1` and watch all the other HPA's fail to get external metrics

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by levan-m** [comment] 2023-12-12 23:01
This is a duplicate of earlier opened issue https://github.com/DataDog/datadog-agent/issues/10216. Please see this [comment](https://github.com/DataDog/datadog-agent/issues/10216#issuecomment-1852944586) on how to address this problem.

**Closed by levan-m** 2023-12-12 23:01 UTC
Labels: team/triage
