### ISSUE TITLE
[BUG] Datadog agent silently corrupts Visual Studio Code and other JavaScript applications on a server

### ISSUE THREAD

**Issue by miohtama** [DataDog/datadog-agent#21882] opened 2024-01-05 10:13 UTC
**Describe what happened:**

Datadog agent silently hooks itself to JavaScript (and Python) applications on a computer. Because the hooks are invasive, and cause side effects and bugs, this will break applications. One of such applications is Visual Studio Code.

**Describe what you expected:**

Any decision to use Datadog agent in an application should be opt-in by the user and datadog-agent should not silently modify any JavaScript (or Python, as it seems) applications. This is because there is a high chance that datadog-agent breaks complex applications, and this causes unnecessary issues for the application maintainers.

**Steps to reproduce the issue:**

- Install Datadog agent
- Try to use [Visual Studio Code - Remote SSH]() on the server
- See [Visual Studio Code ticket](https://github.com/microsoft/vscode/issues/201874)

**Additional environment details (Operating System, Cloud provider, etc):**

```
datadog-agent version
Agent 7.47.1 - Commit: 24dcc70 - Serialization version: v5.0.90 - Go version: go1.20.6
```

```
Description:    Ubuntu 22.04.3 LTS
```

One workaround to this is to delete Datadog and use alternative monitoring solutions where the user has opt-in control to allow a monitoring agent to inject (and potentially break) any application. 

```shell
apt remove datadog-agent
nano /etc/ld.so.preload   # Remove Datadog system level infector
rm -rf /opt/datadog
# Remove the server from Datadog and make sure it is not part of any recurring subscription
```

**Comment by gferreri** [comment] 2024-01-10 14:50
Further noting that running `sudo apt-get remove --purge datadog-agent -y` does not remedy the problem.

**Comment by robbiedhickey** [comment] 2024-01-24 01:37
Over the last two weeks I have had two separate Windows machines have their Visual Studio 2022 installations corrupted. Repairing the installation and uninstalling/reinstalling Visual Studio did not resolve the issue. The only thing that got me back into working order was a fresh install of Windows. 

Reading through this thread made me realize that on both of these machines the `datadog-agent` was installed shortly before I started experiencing problems. 

This sounded similar enough to the issue creator's problem so I wanted to provide another datapoint.

**Comment by michel-smarticket** [comment] 2024-01-29 08:06
> Further noting that running `sudo apt-get remove --purge datadog-agent -y` does not remedy the problem.

@gferreri Did you follow all the steps?

```bash
    apt remove datadog-agent
    nano /etc/ld.so.preload   # Remove Datadog system level infector
    rm -rf /opt/datadog
    # Remove the server from Datadog and make sure it is not part of any recurring subscription
```

I can confirm the issue was fixed once I completely removed the DD agent using the steps above.


@yshapiro-57 Any news on this?

**Comment by anselanza** [comment] 2024-01-29 12:49
I can confirm that removing the Datadog Agent on my remote host also immediately fixed the problems I was having with basic VSCode extensions (e.g. Source Control / Git).

Needless to say, it is very frustrating having to "choose" between running my Datadog agent _or_ having a workable remote development machine. I really hope this one can be sorted out ASAP.

**Comment by Steadyon** [comment] 2024-01-31 20:36
I am having the exact same problem, have spent hours trying to diagnose it before finding [this stackoverflow post](https://stackoverflow.com/questions/76823127/vs-code-not-activating-extensions-error-cannot-find-module-vscode) and finally it all made sense. This is breaking all of my VSCode extensions and stopping me pushing any changes to my github repo as it can't find the repo. 

It was working yesterday when I implemented datadog, but then when I reconnected today this all happened.

**Comment by nhurden** [comment] 2024-03-19 02:54
I was able to workaround this by uninstalling just `datadog-apm-library-js`, leaving the rest of the agent installed (essentially the opposite of https://docs.datadoghq.com/tracing/trace_collection/library_injection_local/?tab=host#install-only-library-injection)

**Comment by KTamas** [comment] 2024-04-02 09:33
This happened to us as well. Very disappointing.

**Comment by alvesdm** [comment] 2024-04-09 17:59
> Over the last two weeks I have had two separate Windows machines have their Visual Studio 2022 installations corrupted. Repairing the installation and uninstalling/reinstalling Visual Studio did not resolve the issue. The only thing that got me back into working order was a fresh install of Windows.
> 
> Reading through this thread made me realize that on both of these machines the `datadog-agent` was installed shortly before I started experiencing problems.
> 
> This sounded similar enough to the issue creator's problem so I wanted to provide another datapoint.

Same here.

My VS 2022 stopped working after installing DD Agent. The only way back was fresh new win install.
At first I though it was only after installing DD agent. Then after a fresh new win install, I first installled DD agent, then right after, VS 2022... and bang! same happened again.

Def smtg up with DD agent.

**Closed** 2024-04-26 13:25 UTC
Labels: team/apm-onboarding

**Comment by Asomeones222** [comment] 2024-11-10 15:38
I couldn't delete Datadog, and since the Datadog Auto inject link above is not wokring, I opted to rename the vscode-server in the home directory to vscode-server-2. After re-installing the extensions everything worked!
