### ISSUE TITLE
fw: frequent Datadog Tracer Errors

### ISSUE THREAD

**Issue by manuel-huez** [DataDog/datadog-agent#2925] opened 2018-03-20 13:40 UTC
(@gbbr asked for the https://github.com/DataDog/dd-trace-go/issues/181 issue to be moved here)

I'm running into a lot of `DataDog Tracer Errors` on the different services we run.

```
Datadog Tracer Error: Post http://dd-agent.kube-system:8126/v0.3/traces: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Datadog Tracer Error: unable to flush traces, lost 500 traces
```

This issue occurs on both of our clusters, both running Kubernetes: one self-managed, the other managed by Tectonic. We don't have connectivity issues between our services.
Please note that this issue is intermittent. We do receive traces on DataDog, but there's always a few that get lost.

```
# go version
go version go1.9.2 darwin/amd64
```

Logs I'm seeing for the trace agent (please note that these are the raw logs, which seem to be trimmed by default):
```
2018-02-20 15:46:35 ERROR (receiver.go:387) - cannot decode v0.3 traces payload: http: unexpected EOF reading trailer
2018-02-20 16:03:14 ERROR (receiver.go:387) - cannot decode v0.3 traces payload: http: unexpected EOF reading trailer
2018-02-20 16:15:46 ERROR (receiver.go:387) - cannot decode v0.3 traces payload: http: unexpected EOF reading trailer
2018-02-20 16:23:27 ERROR (receiver.go:249) - dropping trace reason: invalid span service:"tessellate" name:"middlewares.init" traceID:3108756104495211551 spanID:3108756104495211551 start:15191438...
2018-02-20 16:23:59 ERROR (receiver.go:249) - dropping trace reason: invalid span service:"tessellate" name:"middlewares.init" traceID:7722660901761579816 spanID:7722660901761579816 start:15191438...
2018-02-20 16:24:30 ERROR (receiver.go:249) - dropping trace reason: invalid span service:"tessellate" name:"middlewares.init" traceID:5273839187162951140 spanID:5273839187162951140 start:15191438...
2018-02-20 16:47:31 ERROR (receiver.go:249) - dropping trace reason: invalid span service:"api" resource:"gin.request" traceID:462730192269898272 spanID:462730192269898272 start:151914525074349209...
2018-02-20 16:52:31 ERROR (receiver.go:249) - dropping trace reason: invalid span service:"api" resource:"gin.request" traceID:8229154722886646623 spanID:8229154722886646623 start:1519145550660763...
2018-02-20 17:02:47 ERROR (receiver.go:249) - dropping trace reason: invalid span service:"api" resource:"gin.request" traceID:6913225961392150914 spanID:6913225961392150914 start:1519146167667694...
2018-02-20 17:07:31 ERROR (receiver.go:249) - dropping trace reason: invalid span service:"api" resource:"gin.request" traceID:2321761317779871275 spanID:2321761317779871275 start:1519146450288150...
2018-02-20 17:12:31 ERROR (receiver.go:249) - dropping trace reason: invalid span service:"api" resource:"gin.request" traceID:2285384087229003712 spanID:2285384087229003712 start:1519146750482210...
2018-02-20 17:12:47 ERROR (receiver.go:249) - dropping trace reason: invalid span service:"api" resource:"gin.request" traceID:785244854339271482 spanID:785244854339271482 start:151914676768520044...
2018-02-20 17:16:51 ERROR (receiver.go:387) - cannot decode v0.3 traces payload: unexpected EOF
2018-02-20 17:22:31 ERROR (receiver.go:249) - dropping trace reason: invalid span service:"api" resource:"gin.request" traceID:4294281343579544319 spanID:4294281343579544319 start:1519147350673618...
2018-02-20 17:22:47 ERROR (receiver.go:249) - dropping trace reason: invalid span service:"api" resource:"gin.request" traceID:4852484717936411477 spanID:4852484717936411477 start:1519147367679504...
2018-02-20 17:28:45 ERROR (receiver.go:249) - dropping trace reason: invalid span service:"api" resource:"gin.request" traceID:6983175358650587154 spanID:6983175358650587154 start:1519147723825698...
2018-02-20 17:38:30 ERROR (receiver.go:387) - cannot decode v0.3 traces payload: unexpected EOF
2018-02-20 17:39:11 ERROR (receiver.go:387) - cannot decode v0.3 traces payload: EOF
2018-02-20 17:42:49 ERROR (receiver.go:249) - dropping trace reason: invalid span service:"api" resource:"gin.request" traceID:8705007339549081199 spanID:8705007339549081199 start:1519148567437578...
```

**Comment by tylerbenson** [comment] 2019-01-28 16:14
@vineethvijay That seems like it might be an issue in the [java tracer](https://github.com/datadog/dd-trace-java).  Could you create an issue over there and include steps to reproduce?

Thanks!

**Comment by gbbr** [comment] 2019-01-28 17:06
@manuel-huez unless there is any more input here I'd like to close this issue. I'm more than happy to re-open if you'd like to collaborate.

**Closed by gbbr** 2019-01-28 17:06 UTC
Labels: team/apm

**Comment by rgoomar** [comment] 2019-07-05 21:52
If you want to reduce these errors on environments, you can add the following configuration option:
```
apm_config:
  log_throttling: true
```

**Comment by gbbr** [comment] 2019-07-08 14:05
As an update, `log_throttling` is enabled by default since 6.11.0. Additionally, with the release of 6.13.0, malformed spans will attempt to be fixed, so you won't be seeing anymore of those messages.
