### ISSUE TITLE
[BUG] Nginx access log was manipulated incorrectly by multi-line concatenation behavior

### ISSUE THREAD

**Issue by toan-hf** [DataDog/datadog-agent#32111] opened 2024-12-12 18:30 UTC
**Agent Environment**

agent version 7.59.1
helm version 3.81.0

**Describe what happened:**

Since we upgraded the Datadog-Agent from 7.52.0 to the latest one 7.59.1, the Nginx access log was manipulated incorrectly by multi-line concatenation behavior

![Image](https://github.com/user-attachments/assets/065ccd11-0476-4392-8f84-7984727f953a)

![Image](https://github.com/user-attachments/assets/ff7c5a48-3be9-424d-b19f-bfa9b37cbfb3)

Using agent status, we can quickly identify the log combined is actively working.

![Image](https://github.com/user-attachments/assets/94232ece-e0bd-4edb-8505-714b6d85f1ec)

I think this issue comes from the recent refactoring that was introduced [here](https://github.com/DataDog/datadog-agent/pull/27881/files)

**Describe what you expected:**

The logline should not be combined like the one above, each line should be separated

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

AWS EKS 1.29.0

**Comment by toan-hf** [comment] 2024-12-13 10:23
@gh123man as the recent implemented by your PR, I would love to hear your thought here :)

**Comment by gh123man** [comment] 2024-12-13 14:31
Hi @toan-hf Thanks for the ping! 
Can you share any details around your logs configuration? 

- Are you using `logs_config.auto_multi_line_detection`?
- Do you have a custom regex pattern defined for this log source?

From looking at the screenshot - I can take a guess:

It looks like you may be hitting a case of "mixed format logs" ex: your log file contains both JSON and non JSON logs. 
If you are using `logs_config.auto_multi_line_detection`, this can happen when the agent starts up and detects the wrong pattern, and it can appear to happen somewhat randomly since it is influenced by the applicatio startup behavior. In this case, it looks like it detected the non-JSON log with a timestamp as the "start pattern", and the rest of the JSON logs get combined together incorrectly. 

The code you linked to is actually designed to fix this problem among others. (however it is disabled at the moment while we test it). 

Let me know if my assessment is accurate. If you can confirm the agent configuration settings you are using, I can make some suggestions on how to resolve it.

**Comment by gh123man** [comment] 2024-12-16 14:18
Thanks for confirming the configuration! 

> 3. We rolled back to version 7.52.0, and it seems pretty OK that is why I feel a bit ambiguous about your recent change, I thought it was affected by this, and sorry if my assumption is incorrect

No worries! If you do not expect multiline logs from the nginx source, I would suggest disabling auto multiline detection just on this source. You can do this by setting `auto_multi_line_detection: false` on the logs integration config. ([docs](https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=configurationfile#automatic-multi-line-aggregation)). This will prevent the incorrect aggregation from happening in the future, and you should be able to upgrade to the newer agent version. 

> 4. Speaking about the Nginx log itself, and how it was collected. We often emit the "source": "nginx-ingress-controller" into all the logs of Nginx workload.
> In the Datadog WebUI, the default pipeline (standard one) leans to the source we emitted above.

This sounds reasonable to me. Let me know if my above suggestion works. 
Happy to help!

**Comment by toan-hf** [comment] 2024-12-16 15:58
@gh123man  thanks for your hint. 

The key thing that I am trying to understand a bit further here is what exactly the difference between that `auto_multi_line_detection` when it was 7.52.0 and 7.59.1. 

As far as I can understand, the auto_multi_line_detection on version 7.52.0 was enabled, we set this globally on the Datadog Agent configuration side. In short, auto_multi_line_detection has been applied widely for Nginx Ingress as well as other log sources.
```
logs_config:
  auto_multi_line_detection: true
```

Now when it comes to the new version 7.59.1 if we want to disable that specifically for Ingress Nginx only ,_it is fine but still a bit ambiguous about how this feature actually works_

Appreciate for your insight.

**Comment by gh123man** [comment] 2024-12-19 16:51
> The key thing that I am trying to understand a bit further here is what exactly the difference between that auto_multi_line_detection when it was 7.52.0 and 7.59.1.

There should be no difference. The changes for `auto_multi_line_detection` V2 are independent and don't change the existing behavior. I think the problem is - `auto_multi_line_detection` (v1) is nondeterministic in how it detects a pattern. When the log source restarts or first appears, depending on the distribution of log formats, the agent could choose a different pattern and as a result, change the aggregation behavior. 

NOTE that this particular behavior is fixed in V2 (which we are working on rolling out). Our goal is to remove this ambiguity around how the feature works.

**Comment by toan-hf** [comment] 2024-12-19 17:11
Thank you for your explanation @gh123man, we have had a  chance to revise the code, and what we figured out is quite similar to what you have explained, 
We followed your PR [here](https://github.com/DataDog/datadog-agent/blob/main/pkg/logs/internal/decoder/auto_multiline_detection/timestamp_detector_test.go) and could leverage the Datadog-agent telemetry to identify the log combination feature while the incident occurred

![Image](https://github.com/user-attachments/assets/84cc1983-1329-4a1c-babe-b57f01de2dd9)

As that change introduces a few new patterns that it could match the nginx log format (including JSON access log and ERROR in Syslog format), hence the auto_multi_line_detection was trigged to concatenate many Nginx log lines. 

My last question here would be awesome if you can clarify is: **whether we have any option to disable the log_combination feature individually without disabling the auto_multi_line_detection feature entirely?
if not then when will this feature (auto_multiline_detection v2)is officially rolled out?**

Thank you very much for your guidance.

**Comment by gh123man** [comment] 2024-12-19 17:59
> My last question here would be awesome if you can clarify is: whether we have any option to disable the log_combination feature individually without disabling the auto_multi_line_detection feature entirely?

I hope I am understanding correctly: Yes. 
If you have (in `datadog.yaml`)
```yaml
logs_config:
  auto_multi_line_detection: true
```

you may disable it per source with:
```yaml
logs:
  - type: file
    path: /my/file.log
    service: testApp
    source: java
    auto_multi_line_detection: false
```
(or if in K8s the same way via the pod annotation). 
[Here are the docs that cover this](https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=kubernetes#automatic-multi-line-aggregation)

This will ensure all sources will still use `auto_multi_line_detection` unless it's explicitly disable via the logs integration config. 

> if not then when will this feature (auto_multiline_detection v2)is officially rolled out?

I don't have a firm date, but the feature is complete, and we are just waiting to enable it in the config as we do some extra testing on our end. I'd expect it to be fully released in a few agent versions from now (sometime Early 2025). 


Just a heads up, Ill be away until the new year starting tomorrow so my responses may be delayed. 
I'll hand this thread over to one of my teammates if you have any other questions in the meantime, or always feel free to escalate through Datadog support.

**Comment by toan-hf** [comment] 2024-12-19 18:06
Hmm i understand we can disable multiline detection per service, but what i am asking is I want to disable the feature log_combination individually as it was apart of multiline_detection.
I guess we don't have that for now 

Thank you, we can close this case

**Comment by gh123man** [comment] 2024-12-19 18:10
Ah - yes sorry I misunderstood. 
Today detection and aggregation (combination) are one and the same. 
However - thanks for the feedback and idea. In V2, these concepts are more decoupled so conceptually we could perform detection without actually combining the logs. 

I'll evaluate this and see if it fits into our design as a future feature 👍

**Closed by gh123man** 2024-12-19 18:10 UTC
Labels: team/triage, team/agent-metrics-logs
